# V4 Capability Map

**Scope:** Read-only audit of the Lloyd Engine V4 substrate and eval layer.
**Snapshot date:** 2026-05-30 (git snapshot commit ca25460, covering ~2 weeks of uncommitted work; layer-manifest and test-file evidence are the primary dating sources).
**Source of authority for layer classification:** V4_GLOSSARY.md §3 layer table, LIVE_CAMPAIGNS_LEDGER.md, LAYER_MANIFEST.md / layer_manifest.json, AXIOMS.md.
**Note on confidence:** confidence levels below reflect the quality of evidence available to this audit (direct source reads + confirmed test runs). Claims marked "medium" have indirect or partial test backing.

---

## Table of Contents

1. [L0 Core](#l0-core)
2. [L1 Primitives](#l1-primitives)
3. [L1.5 Projection](#l15-projection)
4. [L2 Metrology](#l2-metrology)
5. [L2 Branch](#l2-branch)
6. [L3a Refinery + History](#l3a-refinery--history)
7. [L3b Solver](#l3b-solver)
8. [Eval Layer](#eval-layer)
9. [Gaps / Not-Yet-Built (aggregate)](#gaps--not-yet-built-aggregate)

---

## L0 Core

**Authoritative status:** Root substrate layer. No parent layers in the manifest. Per CLAUDE.md §1, L0–L2 are "working substrate"; core is the foundational layer from which all others derive (Axiom 12). The layer_manifest.json does not carry an explicit `authoritative` key; the L0 position and zero-parent status are the evidence for treating it as foundational.

**Layer-manifest lineage note:** `core` → parent of all other layers. Provides `status_families`, `value_types`, `protocol_types`, `transition_types`, `errors_and_utilities`. The `__init__.py` exports exactly five transition-machinery symbols, matching the manifest's `all_exports` list. All status families across all layers (including MetrologyStatus, BranchFingerprintStatus, SolverStatus, etc.) are consolidated in `src/lloyd_v4/core/status.py`; per-layer attribution in the manifest is nominal, not enforced at the module boundary.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| Status families — core six | Define and use DomainStatus, StratumStatus, ValidityStatus, ConditioningStatus, ProtocolStatus, ProvenanceStatus as StrEnum members; combine via StatusCode union type alias | Enforce that upper-layer status families live in separate modules — all status families are consolidated in a single file (status.py), making per-layer attribution nominal rather than enforced at module boundaries | tests/test_task000_core_smoke.py (4 tests); tests/test_task005_protocol_status_families.py (4 tests); tests/test_task005_typed_result_generics.py (2 tests) | core → provides status_families: [DomainStatus, StratumStatus, ValidityStatus, ConditioningStatus, ProtocolStatus, ProvenanceStatus] | proven | high |
| TypedResult generic result container | Construct frozen, slotted, generic TypedResult[ValueT, StatusT] carrying value, space, status, validity, conditioning, provenance, protocol, and optional refusal; serialize via to_json_safe() | Enforce value type or StatusT family at runtime (Python generics are erased); provide mutation, merging, or comparison utilities at core level | tests/test_task000_core_smoke.py (test_typed_result_can_hold_typed_refusal, test_protocol_validation_rejects_unhandled_status); tests/test_task005_typed_result_generics.py (2 tests) | core → provides value_types: [TypedResult, TypedRefusal] | proven | high |
| TypedRefusal | Wrap a scalarization refusal as a typed, frozen struct with reason, ProtocolStatus.SCALARIZATION_REFUSED, and optional details dict; serialize to JSON-safe dict | Be used directly as a TypedResult; callers must compose it into TypedResult.refusal manually | tests/test_task000_core_smoke.py (test_typed_result_can_hold_typed_refusal) | core → provides value_types: [TypedResult, TypedRefusal] | proven | high |
| Validity multi-field carrier | Carry up to 5 independent boolean/array fields: defined, finite, selectable, advanceable, observable — each nullable; serialize to JSON-safe dict; implements Axiom 4 | Enforce field semantics or cross-field consistency; "policy-accepted" is not a named Validity field in current implementation; all fields typed as ArrayLike (Any) so no type safety on field values | tests/test_task000_core_smoke.py (indirect via TypedResult construction); tests/test_task005_protocol_status_families.py (required_validity_fields checking) | core → provides value_types: [Validity] | proven | high |
| Conditioning carrier | Carry a ConditioningStatus (WELL_CONDITIONED, ILL_CONDITIONED, SINGULAR, WARNING, UNKNOWN) and optional notes tuple; serialize to JSON-safe dict | Compute condition numbers or derive conditioning from numerical evidence — it is a carrier only | tests/test_task000_core_smoke.py (indirect via TypedResult construction) | core → provides value_types: [Conditioning] | proven | high |
| Provenance with SHA-256 trace_id | Construct frozen provenance record with operation_id, expression_path, precision, backend, device, measurement_resolution, inputs, parents, status; auto-derive 16-hex-char SHA-256 trace_id if not supplied; serialize to JSON-safe dict | Validate that operation_id or expression_path conform to any naming convention; enforce that parents are valid existing trace_ids; trace_id is truncated to 16 chars (collision probability non-zero on very large runs) | tests/test_task000_core_smoke.py (test_provenance_can_be_created_and_serialized); tests/test_task011_provenance_inputs.py (11 tests) | core → provides value_types: [Provenance] | proven | high |
| Protocol contracts — ProducerProtocol and ConsumerProtocol | Define named protocols with emitted_statuses, accepted_statuses, required_validity_fields, scalarization_allowed, and refused_statuses; auto-infer status_family; validate_protocol() checks status-family membership, required validity fields, accepted-status membership, and refusal-scalarization conflict, returning a ProtocolCheck | Check conditioning or provenance fields in validate_protocol; refused_statuses on ConsumerProtocol is defined but not checked inside validate_protocol (only accepted_statuses is checked); scalarization_allowed is checked only in conjunction with a non-None refusal | tests/test_task000_core_smoke.py; tests/test_task005_protocol_status_families.py (4 tests); tests/test_task005_transition_rule_coverage.py | core → provides protocol_types: [ProducerProtocol, ConsumerProtocol, ProtocolCheck]; operations: [validate_protocol] | proven | high |
| Status transition machinery | Define StatusTransitionRule with input/output status families, accepted/refused/mapped status sets, context_keys, and optional callable transition; apply via apply_status_transition() producing StatusTransitionOutcome (MAPPED/ACCEPTED/REFUSED/NOT_APPLICABLE); assert completeness via assert_transition_rule_complete(); serialize to JSON-safe dicts | Chain or compose transition rules; detect cycles; validate that mapped output statuses belong to declared output_status_family at construction time; NOT_APPLICABLE is a silent soft failure (no exception) | tests/test_task005_status_transition_rules.py (3 tests); tests/test_task005_transition_rule_coverage.py (2 tests) | core → provides transition_types: [StatusTransitionRule, TransitionDisposition, StatusTransitionOutcome]; operations: [apply_status_transition, assert_transition_rule_complete] | proven | high |
| Error hierarchy | Raise and catch five named error types rooted at LloydV4Error: ProtocolViolationError, ScalarizationError, HiddenGuardRailError, UnhandledStratumError | Carry structured fields (status code, offending value, rule_id) on the exception — only a message string is carried | tests/test_task005_status_transition_rules.py (ProtocolViolationError on family mismatch); tests/test_task005_protocol_status_families.py; indirect via many upper-layer tests | core → provides errors_and_utilities: [LloydV4Error, ProtocolViolationError, ScalarizationError, HiddenGuardRailError, UnhandledStratumError] | proven | high |
| Status calculus utilities | join_statuses() reduces an iterable of statuses to a single one if all identical, raising ProtocolViolationError on mixed sets; propagate_invalid() passes INVALID/UNKNOWN through; require_handled_status() raises UnhandledStratumError; require_protocol_ok() raises ProtocolViolationError | join_statuses() has no merge/lattice semantics — it is a strict identity check; propagate_invalid() only handles ValidityStatus.INVALID and UNKNOWN; no stratum-awareness | Indirect — exercised via primitives and metrology tests; no dedicated test file for calculus.py specifically | core → provides errors_and_utilities: [join_statuses, propagate_invalid, require_handled_status, require_protocol_ok] | empirical | medium — no dedicated direct test file; coverage is indirect |
| JSON serialization (to_json_safe) | Recursively convert Python structures to JSON-serializable form: floats (encodes nan/inf as {kind: nonfinite_float, value: ...}), Enum (.value), dataclasses (via to_json_safe() if present else asdict), dicts, lists/tuples, sets/frozensets (sorted); ensures allow_nan=False compatibility | Handle numpy arrays, complex numbers, or custom non-dataclass objects that lack to_json_safe() gracefully; provide round-trip deserialization at this layer | tests/test_task000_strict_serialization.py (1 test); tests/test_task011_provenance_inputs.py (11 tests including nested structures) | core → provides errors_and_utilities: [to_json_safe] | proven | high |
| V3 isolation guard (source purity) | Test that no source file in src/ imports lloyd_v3, uses legacy_compat, or defines a safe_mask token | Guard currently fails (1 failure) due to src/lloyd_v4/evals/substrate_invariant_search_phase_e.py referencing lloyd_v3; violation is detectable but not yet resolved; core/ module itself is clean | tests/test_task000_no_v3_dependency.py (2 tests: 1 failing on evals file, 1 passing for safe_mask) | core — structural isolation rule (Axiom 10) | partial | high — failure confirmed by test run; core/ itself clean |

---

## L1 Primitives

**Authoritative status:** Operationally authoritative. V4_GLOSSARY.md §3 layer table marks L1 Primitives as "Complete" (no partial qualifier). All 7 primitive modules are implemented, test-passing, and actively consumed by higher layers. Source purity failures in test_task001_source_purity and test_task002 are caused by evals/ files, not by any primitives/ file; primitives/ is source-clean.

**Layer-manifest lineage note:** `primitives` parent = [core]; observers (L1.5) and projection (L1.5) parent = [core, primitives]. Seven primitive modules plus internal operations (typed_log_log_slope). Three identified gaps in the manifest for this layer: GAP-001 (typed_sqrt), GAP-002 (typed_log), GAP-004 (typed_bacl_grain) — all absent from src/lloyd_v4/primitives/. GAP-009 (L1 atomicity policy) resolved by relocating probe operations to L1.5 observers.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| typed_collection | Wrap arbitrary iterable into typed result with strata: COLLECTION_EMPTY (selectable=false), COLLECTION_SINGLETON, COLLECTION_OBSERVED; full provenance; serialise via to_json_safe | Order, slice, or validate element types beyond presence; advanceable is always false | tests/test_task010_sub_a_typed_collection.py — 6 tests, all passing | primitives (parent: core); calibrated_primitive_operations | complete | high |
| typed_value | Wrap single raw value (None or non-None) into typed result with strata VALUE_ABSENT / VALUE_OBSERVED; NON_NULL_TYPED_VALUE_PROTOCOL consumer enforces presence gate; serialise via to_json_safe | Inspect type beyond None-check; validate finiteness or numeric range; advanceable always false | tests/test_task010_sub_b_typed_value.py — 7 tests, all passing | primitives (parent: core); calibrated_primitive_operations | complete | high |
| typed_ulp | Compute IEEE 754 local lattice spacing at a float via bit manipulation (stdlib math + struct only); supports float64 and float32; six strata: ULP_NORMAL, ULP_SUBNORMAL, ULP_ZERO, ULP_AT_EDGE, ULP_NONFINITE_INF, ULP_NONFINITE_NAN; returns binade index, is_subnormal, format label; FINITE_TYPED_ULP_PROTOCOL consumer gates on finite strata; TypedRefusal for non-finite inputs; fully provenance-tracked | float16, bfloat16, or other precisions (ValueError raised); ULP_AT_EDGE is not finite/selectable; no multi-precision simultaneous query | tests/test_typed_ulp.py — 45 tests, all passing (26 float64 + 18 float32 + 1 dispatcher) | primitives (parent: core); calibrated_primitive_operations | complete | high |
| projective_ratio | Construct ProjectiveRatio(n, d) with strata: FINITE_RATIO, SIGNED_ZERO, INFINITE_DIRECTION, INDETERMINATE; accepts raw scalars or TypedResult inputs; carries precision/backend/device/measurement_resolution in provenance | Detect near-zero denominators or cancellation — classification is algebraically exact zero only; no finiteness check on inputs; no numeric type enforcement beyond equality-to-zero | tests/test_task001_projective_ratio.py (6), test_task001_projective_ratio_scalarization.py (4), test_task001_projective_ratio_serialization.py (2) — 12 tests, all passing | primitives (parent: core); calibrated_primitive_operations; PROJECTIVE_RATIO_SCALARIZATION_TRANSITION_RULE registered | complete | high |
| scalarize_projective_ratio | Consume a ProjectiveRatioResult, validate against PROJECTIVE_RATIO_SCALARIZATION_PROTOCOL (accepts FINITE_RATIO and SIGNED_ZERO), emit scalar quotient in new TypedResult with SCALAR_SPACE; refuse INFINITE_DIRECTION and INDETERMINATE via TypedRefusal; provenance chains parent trace_id | Handle inputs not from projective_ratio (raises TypeError); provide partial-scalarization or tolerance-based acceptance | tests/test_task001_projective_ratio_scalarization.py (4 tests, all passing) | primitives (parent: core); internal_operations (projective_ratio.scalarize) — not a standalone calibrated primitive | complete | high |
| stratified_quadratic_roots | Solve ax²+bx+c=0 with strata: TWO_REAL_ROOTS, REPEATED_ROOT (conditioning WARNING), NO_REAL_ROOT, LINEAR_ROOT, CONSTANT_IDENTITY, CONSTANT_NO_SOLUTION; stores discriminant and per-branch ProjectiveRatioValue coordinates; requires finite real scalar inputs; carries precision/backend/device metadata | Accept numpy scalars or complex types (only Python int or float); detect near-degenerate cases numerically — classification is algebraic only; multi-precision backend | tests/test_task002_stratified_quadratic_roots.py (9), test_task002_quadratic_root_serialization.py (4) — 13 tests, all passing | primitives (parent: core); calibrated_primitive_operations; QUADRATIC_ROOT_SELECTION_TRANSITION_RULE registered | complete | high |
| select_quadratic_root | Select named branch ('minus'/'plus' for TWO_REAL_ROOTS, 'repeated' for REPEATED_ROOT, 'linear' for LINEAR_ROOT) from StratifiedQuadraticRootResult; validate via QUADRATIC_ROOT_SELECTION_PROTOCOL; call projective_ratio + scalarize_projective_ratio internally; return scalar TypedResult; refuse incompatible branches or non-selectable root states with TypedRefusal; full provenance chain | Select from NO_REAL_ROOT, CONSTANT_IDENTITY, or CONSTANT_NO_SOLUTION; enumerate branches programmatically (branch names are fixed strings) | tests/test_task002_quadratic_root_selection.py (4 tests, all passing) | primitives (parent: core); internal_operations (stratified_quadratic_roots.select) — not a standalone calibrated primitive | complete | high |
| typed_finite_difference | Compute T_{delta_f}(f) = (g(f+delta_f) - g(f)) / delta_f as typed observation; strata: TRANSFER_OBSERVED, TRANSFER_CANCELLATION_DOMINATED (cancellation_ratio < 2^-52), TRANSFER_NON_FINITE, TRANSFER_DOMAIN_REFUSED, TRANSFER_DELTA_INDETERMINATE; computes cancellation_ratio; handles exceptions from g_callable gracefully; TRANSFER_OBSERVATION_CONSUMER_PROTOCOL gates on TRANSFER_OBSERVED only | Only precision='raw_python' (any other value raises ProtocolViolationError); no backward or central difference variants; cancellation floor is hardcoded to 2^-52; forward difference only | tests/test_task015_typed_finite_difference.py — 25 tests, all passing | primitives (parent: core); calibrated_primitive_operations | complete | high |
| typed_log_log_slope | Fit OLS log-log slope to a TypedCollectionResult of TransferObservationResult items; filters to TRANSFER_OBSERVED with positive f_value and non-zero finite transfer; requires n_used >= 3; returns LogLogSlopeObservation with slope, intercept, r_squared, standard_error, n_input/n_used, log_f bounds; strata: SLOPE_OBSERVED, SLOPE_INSUFFICIENT_DATA, SLOPE_DEGENERATE_INPUT; provenance chains parent trace_id plus all constituent item trace_ids | Only OLS — no weighted, robust, or confidence-interval output; minimum 3 TRANSFER_OBSERVED points; negative or zero f_values silently dropped; not exposed as calibrated primitive — internal operation only | tests/test_task016_typed_log_log_slope.py — 24 tests, all passing | primitives (parent: core); internal_operations — orchestrates sibling primitives; boundary case per GAP-009 L1 atomicity policy | complete | high |
| typed_sqrt (GAP-001) | (Not implemented) | No substrate-native typed square root primitive exists; consumers use ad-hoc math.sqrt calls; blocked on GAP-009 L1 atomicity policy resolution (must resolve before Transplant 3) | none found | Not listed in primitives layer manifest; identified as GAP-001 in Reports/task050/parent_primitive_gaps.md | open | high |
| typed_log (GAP-002) | (Not implemented) | No substrate-native typed natural log primitive exists; blocked on GAP-009 L1 atomicity policy resolution | none found | Not listed in primitives layer manifest; identified as GAP-002 in Reports/task050/parent_primitive_gaps.md | open | high |
| typed_bacl_grain (GAP-004) | (Not implemented) | No typed BACL grain primitive exists; the BACL invariant (a-b = j*ulp(b) for aligned floats) is empirically proven (31,000+ records) but has no typed L1 slot; consumers access via ad-hoc implementations in evals/ and scratch/; depends on typed_ulp (GAP-003, now resolved) | none found | Not listed in primitives layer manifest; identified as GAP-004 in Reports/task050/parent_primitive_gaps.md | open | high |

---

## L1.5 Projection

**Authoritative status:** Authoritative. V4_GLOSSARY.md §3 layer table marks L1.5 Projection as "Complete" — no partial qualifier (that is L3's label) and no "operationally authoritative" qualifier (that is L2's specific designation). All operations are implemented, test-backed, and actively consumed by higher layers.

**Layer-manifest lineage note:** `projection` parent = [core, primitives]. Zero calibrated_primitive_operations and zero internal_operations per the manifest; both operations (branch_selection, exact_quadratic_projection) are consumer/producer operations. The `_projection_branch.py` helper under tests/ is a shared fixture module, not a test file. Status families: [ProjectionStatus] (7 emitted statuses).

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| BranchSelection enum construction | Wrap a BranchSelection enum member (MINUS, PLUS, REPEATED, LINEAR) into a typed BranchSelectionResult carrying VALUE_OBSERVED, with full provenance lineage from the inner typed_value primitive | Accept raw strings in place of BranchSelection members (raises ProtocolViolationError); produce any status other than VALUE_OBSERVED; select a branch automatically | tests/test_task010_rebuild_projection_branch_selection.py (3 tests): construction, raw-string rejection, protocol validation | projection → primitives (typed_value) → core; listed under projection.provides.operations as branch_selection | complete | high |
| Exact quadratic projection — transverse stratum | Given TWO_REAL_ROOTS root-state result and MINUS or PLUS BranchSelectionResult, emit ProjectionResultV4 with status PROJECTION_TRANSVERSE, selected root value, full provenance chain (root, branch, selected-root trace IDs) | Select a root without MINUS/PLUS branch (incompatible branch yields PROJECTION_SELECTION_REFUSED); operate on coefficients directly; advance past a tangent contact | tests/test_task010_rebuild_projection_strata_scenarios.py (3 tests), test_task010_rebuild_projection_result.py (2 tests), test_task010_rebuild_projection_serialization.py (2 tests) | projection → primitives (stratified_quadratic_roots, select_quadratic_root) → core; exact_quadratic_projection operation | complete | high |
| Exact quadratic projection — tangent-contact stratum | For REPEATED_ROOT root-state with REPEATED branch, emit PROJECTION_TANGENT_CONTACT with advanceable=False and conditioning WARNING; root value selected and traced | Accept MINUS/PLUS branch against repeated root (yields PROJECTION_SELECTION_REFUSED); advance from this stratum (validity.advanceable is explicitly False) | tests/test_task010_rebuild_projection_strata_scenarios.py (test_selectable_strata_project_to_expected_statuses asserts advanceable=False for repeated) | projection → primitives → core; PROJECTION_TANGENT_CONTACT listed in PROJECTION_RESULT_V4_PROTOCOL | complete | high |
| Exact quadratic projection — linear stratum | For LINEAR_ROOT root-state with LINEAR branch, emit PROJECTION_LINEAR with full validity (defined, finite, selectable, advanceable, observable) and selected root value traced | Accept MINUS/PLUS/REPEATED branch against a linear root (yields PROJECTION_SELECTION_REFUSED) | tests/test_task010_rebuild_projection_strata_scenarios.py | projection → primitives → core; PROJECTION_LINEAR listed in PROJECTION_RESULT_V4_PROTOCOL | complete | high |
| Exact quadratic projection — non-selectable strata | For NO_REAL_ROOT, CONSTANT_IDENTITY, or CONSTANT_NO_SOLUTION root-state results, emit corresponding projection status (PROJECTION_NO_REAL_ROOT, PROJECTION_IDENTITY, PROJECTION_NO_SOLUTION) with selected_root_trace_id=None and validity.defined=False | Select a root value in any of these strata; emit any non-None selected_root_value | tests/test_task010_rebuild_projection_strata_scenarios.py (test_nonselectable_strata_project_without_selection) | projection → primitives → core; PROJECTION_NO_REAL_ROOT, PROJECTION_IDENTITY, PROJECTION_NO_SOLUTION all listed in PROJECTION_RESULT_V4_PROTOCOL | complete | high |
| Protocol-guarded projection input validation and typed refusal | Validate root-state result against EXACT_QUADRATIC_PROJECTION_PROTOCOL; validate branch result against BRANCH_SELECTION_CONSUMER_PROTOCOL; if either fails, emit TypedRefusal (PROJECTION_SELECTION_REFUSED) with reason, details, and provenance linking both parents; handles wrong Python types, wrong status families, refused statuses | Accept non-TypedResult inputs (raises ProtocolViolationError, not a typed refusal); accept ProjectiveRatioResult where StratifiedQuadraticRootValue is required | tests/test_task010_rebuild_projection_protocol.py (3 tests): wrong python types, wrong status on root result, wrong status on branch result; tests/test_task005_status_transition_rules.py; tests/test_task005_transition_rule_coverage.py (2 tests) | projection → core (validate_protocol, apply_status_transition, ProtocolViolationError); EXACT_QUADRATIC_PROJECTION_PROTOCOL and BRANCH_SELECTION_CONSUMER_PROTOCOL listed in projection.provides.protocol_types | complete | high |
| Contextual status transition rule (QUADRATIC_ROOT_TO_EXACT_PROJECTION_TRANSITION_RULE) | Map every QuadraticRootStatus to a ProjectionStatus via branch-contextual transition rule (rule_id 'quadratic_roots.to_exact_projection'); branch-incompatible pairs emit PROJECTION_SELECTION_REFUSED; rule completeness is testable | Produce a static coverage map that fully captures branch-conditional refusals — the static mapped_statuses dict is guidance only; runtime callable is authoritative | tests/test_task005_transition_rule_coverage.py (2 tests); tests/test_task005_status_transition_rules.py (test_projection_contextual_transition_rule) | projection.provides.transition_types lists QUADRATIC_ROOT_TO_EXACT_PROJECTION_TRANSITION_RULE | complete | high |
| Projection result serialization (to_json_safe) | Serialize ProjectionResultV4 (success or refusal) to JSON-safe dict with no NaN/Infinity values, no flags field, no embedded refusal inside value (refusal lives only at top-level TypedResult.refusal); covers both successful projection and PROJECTION_SELECTION_REFUSED | Serialize in any format other than the to_json_safe protocol; schema validation beyond the to_json_safe contract | tests/test_task010_rebuild_projection_serialization.py (2 tests) | projection → core (to_json_safe); ProjectionResultValue.to_json_safe listed implicitly via value_types | complete | high |
| Provenance chain threading through projection | Carry precision, backend, device, and measurement_resolution metadata from root-state provenance through projection result; parent trace IDs include: root_state trace_id, branch_selection trace_id, and (for selectable strata) selected_root trace_id | Re-derive or override precision/backend; introduce new precision metadata at this layer (no calibrated_primitive_operations in manifest) | tests/test_task010_rebuild_projection_result.py (test_projection_result_has_no_flags_or_value_refusal_duplication) | projection.provides.calibrated_primitive_operations: [] (empty); provenance threading relies on core.Provenance | complete | high |
| Scalarization gate (scalarization_allowed=False) | Enforce that neither root-state nor branch inputs may have been produced via a scalarization path; EXACT_QUADRATIC_PROJECTION_PROTOCOL sets scalarization_allowed=False | Provide a scalarization escape hatch; process root-states produced by scalarize_projective_ratio without protocol violation | Enforced structurally via ConsumerProtocol(scalarization_allowed=False); indirectly covered by test_task010_rebuild_projection_protocol.py; no dedicated scalarization-gate test found | projection → core (ConsumerProtocol, validate_protocol); both protocols set scalarization_allowed=False | proven | medium — no dedicated scalarization-gate test |

---

## L2 Metrology

**Authoritative status:** Operationally authoritative. V4_GLOSSARY.md §3 (line 119): "L2 Metrology / Branch: Complete; operationally authoritative." LAYER_MANIFEST.md metrology stanza is the primary manifest source.

**Layer-manifest lineage note:** `metrology` parent = [core, primitives]. Provides calibrated_primitive_operations: [declare_bk_noise_floor, estimate_bk_noise_floor, proxy_uncalibrated]; operations: [classify_against_noise_floor, calibrate_proxy_kq, require_valid_proxy_calibration]; transition_types: [LIMIT_OF_DETECTION_TRANSITION_RULE, VALID_PROXY_CALIBRATION_TRANSITION_RULE]; status_families: [MetrologyStatus]. Note: MetrologyStatus is defined in src/lloyd_v4/core/status.py (line 37), not in the metrology module itself — the manifest attribution is nominal. 28 test files import from lloyd_v4.metrology; 6 dedicated test_task004_* files (25 test functions) form the core test suite.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| declare_bk_noise_floor | Produce typed NoiseFloorResult (status=NOISE_FLOOR_DECLARED) from caller-asserted finite nonneg floor value; carries label, unit, optional measurement_resolution, method='declared', sample_count=0, empty observations tuple; validity: defined/finite/selectable/observable=True, advanceable=False; conditioning: WELL_CONDITIONED; rejects negative, non-finite, or boolean inputs with ProtocolViolationError | Derive a floor from observations (that is estimate_bk_noise_floor); accept zero floor and promote to identity_zero — requires separate classify step with identity_evidence=True; produce multi-resolution or per-path floor evidence | tests/test_task004_bk_noise_floor.py (~6 direct tests); tests/test_task004_metrology_serialization.py (3 tests); tests/test_task004_no_reclassification.py (1 test) | metrology (parent: core, primitives); calibrated_primitive_operations | complete | high |
| estimate_bk_noise_floor | Produce typed NoiseFloorResult from sequence of finite real observations using 'max_abs_observed' (floor = max(|obs_i|)); NOISE_FLOOR_ESTIMATED with sample_count when non-empty; NOISE_FLOOR_INDETERMINATE with noise_floor=None when empty; conditioning: WARNING in both cases; rejects non-finite observations or any method other than 'max_abs_observed' | Only 'max_abs_observed' method implemented; 'median', 'quantile', 'mean', 'percentile' raise ProtocolViolationError; cannot produce WELL_CONDITIONED output; zero observations yields INDETERMINATE | tests/test_task004_bk_noise_floor.py (test_estimated_noise_floor_uses_max_abs_observed, test_empty_observations_are_indeterminate, test_invalid_observation_or_method_rejected, test_all_zero_observations_estimate_zero_but_do_not_certify_identity); test_task004_metrology_serialization.py | metrology (parent: core, primitives); calibrated_primitive_operations | complete | high |
| classify_against_noise_floor | Consume typed NoiseFloorResult (must satisfy LIMIT_OF_DETECTION_PROTOCOL) and scalar finite real observable; produce typed LimitOfDetectionResult; strata: DETECTED, BELOW_LIMIT_OF_DETECTION, DETECTION_INDETERMINATE, IDENTITY_ZERO; carries noise_floor_trace_id; rejects non-TypedResult or wrong-family inputs; rejects nonzero observable when identity_evidence=True | Classify a vector or batch in one call; accept raw floats or wrong-family TypedResult as floor evidence; emit DETECTED_NONZERO (that status exists in MetrologyStatus but is not emitted by any classify path in current implementation); produce advanceable=True validity | tests/test_task004_bk_noise_floor.py (test_limit_of_detection_classification_semantics, test_identity_evidence_requires_exact_zero, test_zero_observable_with_zero_floor_is_indeterminate_without_identity, test_detection_rejects_raw_or_unrelated_floor_evidence, test_all_zero_observations_estimate_zero_but_do_not_certify_identity); test_task004_metrology_serialization.py (3 tests); test_task004_no_reclassification.py (1); test_task005_protocol_status_families.py; test_task005_existing_flows_still_pass.py (2); test_task006_slope_flow_direct.py; test_task009a_metrology_policy_scenarios.py (1) | metrology (parent: core, primitives); operations (consumer operation, not calibrated_primitive_operation); transition rule: LIMIT_OF_DETECTION_TRANSITION_RULE | complete | high |
| calibrate_proxy_kq | Produce typed ProxyCalibrationResult by computing projective ratio of (proxy_observable, transfer_observable) via L1 projective_ratio, then attempting scalarization; strata: CALIBRATION_VALID (finite nonzero Kq scalar), CALIBRATION_INVALID (zero proxy or zero transfer), CALIBRATION_INDETERMINATE (0/0); carries kq_projective_coordinates, both trace IDs, and refusal_evidence; never emits NaN/Inf as numeric values; accepts optional label metadata | Produce multi-point or sweep calibration — pointwise only; accept non-finite inputs (ProtocolViolationError); produce WELL_CONDITIONED for non-VALID statuses; aggregate across frequencies | tests/test_task004_kq_calibration.py (5 tests); test_task004_metrology_serialization.py (test_kq_and_uncalibrated_serialization); test_task004_metrology_protocols.py (3 tests); test_task005_existing_flows_still_pass.py; test_task006_branch_fingerprint.py, test_task006_kq_slope_stability.py, test_task006_serialization.py, test_task007_refinery_snapshot.py | metrology (parent: core, primitives); operations (not calibrated_primitive_operation); uses primitives.projective_ratio | complete | high |
| proxy_uncalibrated | Produce typed ProxyCalibrationResult with status=PROXY_UNCALIBRATED, representing missing/absent calibration evidence as a typed first-class result; validity: all False except observable=True; accepts proxy_label and reason string; carries ProxyCalibrationValue with all numeric fields None | Be accepted by VALID_PROXY_CALIBRATION_PROTOCOL; carry any numeric Kq evidence; propagate a trace from any upstream computation | tests/test_task004_kq_calibration.py (test_proxy_uncalibrated_is_typed_missing_evidence); test_task004_metrology_protocols.py; test_task004_metrology_serialization.py; test_task006_kq_slope_stability.py | metrology (parent: core, primitives); calibrated_primitive_operations | complete | high |
| require_valid_proxy_calibration | Consumer gate: accept ProxyCalibrationResult against VALID_PROXY_CALIBRATION_PROTOCOL (accepted_statuses={CALIBRATION_VALID}); on acceptance promote to ValidProxyCalibrationValue carrying kq_scalar_value, parent_calibration_trace_id, label strings; on refusal return TypedResult with SCALARIZATION_REFUSED and TypedRefusal; reject non-TypedResult or wrong-family inputs with ProtocolViolationError | Accept CALIBRATION_INVALID, CALIBRATION_INDETERMINATE, or PROXY_UNCALIBRATED; produce scalar Kq from non-valid calibration; perform aggregation or stability assessment | tests/test_task004_metrology_protocols.py (3 tests); test_task005_protocol_status_families.py; test_task005_existing_flows_still_pass.py (2 tests); VALID_PROXY_CALIBRATION_TRANSITION_RULE tested in test_task005_status_transition_rules.py and test_task005_transition_rule_coverage.py | metrology (parent: core, primitives); operations; transition rule: VALID_PROXY_CALIBRATION_TRANSITION_RULE | complete | high |
| MetrologyStatus enum and status families | Provide full MetrologyStatus StrEnum with 12 members including IDENTITY_ZERO, BELOW_LIMIT_OF_DETECTION, DETECTED_NONZERO, NOISE_FLOOR_DECLARED, NOISE_FLOOR_ESTIMATED, NOISE_FLOOR_INDETERMINATE, DETECTED, DETECTION_INDETERMINATE, CALIBRATION_VALID, CALIBRATION_INVALID, CALIBRATION_INDETERMINATE, PROXY_UNCALIBRATED; all statuses carry typed Validity and Conditioning mappings | DETECTED_NONZERO is declared in the enum but is not emitted by any operation in the metrology module — no code path in noise_floor.py or proxy_calibration.py produces it; it is a reserved/legacy status with no current emitting operation | tests/test_task004_bk_noise_floor.py and test_task004_kq_calibration.py cover all emitted statuses; test_task005_protocol_status_families.py (4 tests); DETECTED_NONZERO: no test found that emits or exercises it from metrology operations | metrology (parent: core, primitives); status_families: [MetrologyStatus]; defined in core/status.py | partial | high — DETECTED_NONZERO gap confirmed |
| Layer isolation / source purity | L2 metrology imports only from core and primitives; earlier layers prohibited from importing metrology terms — enforced by test; no direct Kq division in metrology source; no V3, epsilon, clamp_min, or legacy_compat tokens | Import from projection, observers, branch, refinery, history, or solver; compute Kq via direct division | tests/test_task004_source_purity.py (3 tests); tests/test_task003_source_purity.py | metrology (parent: core, primitives) per layer_manifest.json | proven | high |
| Serialization (to_json_safe / JSON round-trip) | All NoiseFloorValue, LimitOfDetectionValue, and ProxyCalibrationValue carry to_json_safe(); non-finite floats encoded as {kind: 'nonfinite_float', ...} sentinel dicts; allow_nan=False compatibility | Produce standard JSON Infinity/NaN literals (by design); binary or msgpack serialization | tests/test_task004_metrology_serialization.py (3 tests) | Serialization utility from core; metrology value types implement to_json_safe() directly | complete | high |
| Transition rules (LIMIT_OF_DETECTION_TRANSITION_RULE, VALID_PROXY_CALIBRATION_TRANSITION_RULE) | Both rules are registered StatusTransitionRule objects with explicit rule_id, input/output status families, accepted/refused/mapped status sets, context_keys; both registered in layer manifest | No automated rule-completeness check at module import time; LIMIT_OF_DETECTION_TRANSITION_RULE has context-dependent _limit_transition function whose mapped_statuses dict shows only default — actual behavior depends on runtime context | tests/test_task005_status_transition_rules.py (test_metrology_transition_rules — 1 of 3); tests/test_task005_transition_rule_coverage.py (2 tests); full round-trip via test_task004_bk_noise_floor and test_task004_metrology_protocols | metrology (parent: core, primitives); transition_types: [LIMIT_OF_DETECTION_TRANSITION_RULE, VALID_PROXY_CALIBRATION_TRANSITION_RULE] | complete | high |

---

## L2 Branch

**Authoritative status:** Operationally authoritative. V4_GLOSSARY.md §3 (line 119): "L2 Metrology / Branch: Complete; operationally authoritative."

**Layer-manifest lineage note:** `branch` parent = [core, primitives, projection, metrology]. Two source files (fingerprint.py, slope_flow.py). Manifest lists compare_slope_flow_to_models as the only calibrated_primitive_operation; compare_kq_slope_stability and build_branch_fingerprint are composed operations. Status family: BranchFingerprintStatus (16 members in three frozensets). Five transition rules. Five protocol declarations. 6 dedicated task006 test files (13 test functions total) plus 3 integration test files from task007/009.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| compare_slope_flow_to_models | Accept sequence of SlopeFlowSample objects; filter usable samples; compute log-log slope for every adjacent pair via projective_ratio + scalarize_projective_ratio; emit SlopeFlowComparisonResult with 8 possible BranchFingerprintStatus strata (SLOPE_FLOW_OBSERVED, SLOPE_MODEL_RESIDUALS, SLOPE_MODEL_UNIQUE_MATCH, SLOPE_MODEL_AMBIGUOUS, SLOPE_MODEL_NO_MATCH, SLOPE_FLOW_INSUFFICIENT_SAMPLES, SLOPE_FLOW_INDETERMINATE, SLOPE_FLOW_PROXY_UNCALIBRATED); full provenance parent chain through segment projective trace IDs; JSON-serialisable; no NaN/Infinity sentinels | Infer model candidates autonomously; handle non-log-linear phenomena; merge or aggregate across multiple separate flow results; propagate SLOPE_FLOW_PROXY_UNCALIBRATED internally (it is reserved for upstream callers); operate on negative or zero control values; multi-variate slope analysis | tests/test_task006_slope_flow_direct.py (3 tests: SLOPE_FLOW_OBSERVED, model match/ambiguous/no-match, insufficient/indeterminate/detection filter); tests/test_task006_branch_fingerprint.py (2 tests); tests/test_task006_serialization.py (1 test); tests/test_task006_transition_rules.py (2 tests) | branch (parent: core, primitives, projection, metrology); calibrated_primitive_operations; uses primitives.projective_ratio and scalarize_projective_ratio | proven | high — 7 of 8 slope-flow statuses exercised by direct tests; SLOPE_FLOW_PROXY_UNCALIBRATED is defined but not internally emitted |
| compare_kq_slope_stability | Accept parallel sequences of control values and ProxyCalibrationResult objects; validate each via require_valid_proxy_calibration; any refusal yields KQ_FLOW_UNCALIBRATED; with >=2 samples and declared_stability_band: run compare_slope_flow_to_models internally, check segment slopes within band; strata: KQ_FLOW_STABLE, KQ_FLOW_UNSTABLE, KQ_FLOW_INDETERMINATE, KQ_FLOW_UNCALIBRATED; full provenance chain; JSON-serialisable | Assess stability with non-positive or non-finite control values (ProtocolViolationError); accept non-ProxyCalibrationResult objects; weight, window, or trend-detect beyond per-segment slope comparison; emit KQ_FLOW_STABLE without declared_stability_band; joint stability across multiple K_q dimensions | tests/test_task006_kq_slope_stability.py (3 tests: stable/unstable, indeterminate, uncalibrated + wrong-family rejection); tests/test_task006_branch_fingerprint.py (1 test); tests/test_task006_serialization.py (1 test) | branch (parent: core, primitives, projection, metrology); operations (composed, not calibrated_primitive_operation) | proven | high — all 4 KQ_FLOW_* statuses exercised |
| build_branch_fingerprint | Compose ProjectionResultV4 and SlopeFlowComparisonResult (plus optional KqSlopeStabilityResult) into BranchFingerprintResult; apply PROJECTION_TO_FINGERPRINT_TRANSITION_RULE and TRANSFER_FLOW_TO_FINGERPRINT_TRANSITION_RULE; strata: FINGERPRINT_COMPLETE, FINGERPRINT_UNIDENTIFIED, FINGERPRINT_INCOMPLETE, FINGERPRINT_PROXY_UNCALIBRATED; carry projection_trace_id, transfer_flow_trace_id, transfer_selected_model_name, observable_kind, kq_flow_trace_id, fingerprint_components dict, source_trace_ids | Validate observable_kind values other than 'direct_transfer' or 'proxy' (ProtocolViolationError); compose more than two evidence arms; introspect or re-run constituent analyses; produce a 'partial' fingerprint simultaneously COMPLETE and UNIDENTIFIED; multi-branch or ensemble fingerprinting; FINGERPRINT_INCOMPLETE is not selectable (validity.selectable=False) | tests/test_task006_branch_fingerprint.py (2 tests covering all 4 FINGERPRINT_* statuses); tests/test_task006_serialization.py (1 test); tests/test_task009_solver_branch_and_refinery_gates.py (4 tests, integration); tests/test_task009a_branch_refinery_gate_scenarios.py (2 tests) | branch (parent: core, primitives, projection, metrology); operations (composed); output consumed by refinery (BRANCH_FINGERPRINT_STATUS_PRESERVATION_TRANSITION_RULE) and solver (BRANCH_FINGERPRINT_TO_SOLVER_TRANSITION_RULE) | proven | high — all 4 FINGERPRINT_* output statuses tested; proxy path tested |
| BranchFingerprintStatus family (16 members) | Define and use complete closed status vocabulary: 8 slope-flow statuses, 4 kq-flow statuses, 4 fingerprint statuses; three frozensets (KQ_FLOW_STATUSES, FINGERPRINT_STATUSES, SLOPE_FLOW_STATUSES) partition the family; status families mutually exclusive groups enforced by transition rules | Encode a total ordering or numeric severity; provide 'merge' or 'aggregate' operation across family members; SLOPE_FLOW_PROXY_UNCALIBRATED is defined but not internally emitted by branch operations | tests/test_task006_transition_rules.py (2 tests); tests/test_task006_kq_slope_stability.py (3 tests cover all KQ_FLOW_*); tests/test_task006_slope_flow_direct.py (3 tests cover 7 of 8 slope-flow); tests/test_task006_branch_fingerprint.py (2 tests cover all 4 FINGERPRINT_*) | branch (parent: core, primitives, projection, metrology); status_families: [BranchFingerprintStatus]; defined in lloyd_v4.core.status; frozenset partitions declared in branch module | complete | high — full family visible in source; frozenset partitions verified against status enum members |
| Transition rule suite (5 rules) | Provide 5 StatusTransitionRule objects covering all branch protocol boundaries: SLOPE_FLOW_MODEL_COMPARISON, KQ_FLOW_REQUIRE_STABLE, PROJECTION_TO_FINGERPRINT, TRANSFER_FLOW_TO_FINGERPRINT, BRANCH_COMPOSE_FINGERPRINT; all satisfy assert_transition_rule_complete | Self-execute rules without apply_status_transition call; dynamically create or mutate rules at runtime; encode sequencing constraints; BRANCH_COMPOSE_FINGERPRINT_TRANSITION_RULE has empty refused_input_statuses (accepts all FINGERPRINT_STATUSES), requiring downstream selectability logic | tests/test_task006_transition_rules.py (2 tests: assert_transition_rule_complete on all 5 rules; wrong-family ProtocolViolationError) | branch (parent: core, primitives, projection, metrology); transition_types: [all 5 rules] | proven | high — assert_transition_rule_complete is a completeness-proving test helper; all 5 rules pass |
| Protocol declarations (5 protocols) | Declare 5 named protocols: KQ_SLOPE_STABILITY_PROTOCOL, BRANCH_FINGERPRINT_PROTOCOL, BRANCH_FINGERPRINT_CONSUMER_PROTOCOL, SLOPE_FLOW_COMPARISON_PROTOCOL, SLOPE_FLOW_CONSUMER_PROTOCOL; all branch TypedResult outputs carry protocol=ProtocolStatus.OK | Enforce protocol fields at call time beyond what validate_protocol is explicitly called with; version or deprecate protocol objects; runtime schema validation of TypedResult field contents | tests/test_task006_transition_rules.py (protocol IDs verified implicitly via assert_transition_rule_complete); tests/test_task010a_layer_manifest_machine_readable.py (manifest-completeness checks) | branch (parent: core, primitives, projection, metrology); protocol_types: [all 5 protocols] | complete | high |
| Validity and Conditioning assignment per status | Assign multi-field Validity and Conditioning on all branch TypedResult outputs per Axiom 4; slope-flow good statuses: defined=True, finite=True, selectable=True, advanceable=False, observable=True; bad statuses: selectable=False or defined=False; Conditioning: WELL_CONDITIONED for terminal good statuses; WARNING for all others | advanceable is always False for all branch outputs; no branch output marked policy_accepted; observable always True for all branch results | tests/test_task006_slope_flow_direct.py (1 test checks validity.defined=True for SLOPE_FLOW_OBSERVED); tests/test_task006_branch_fingerprint.py (implicitly); no dedicated validity-field exhaustive test for branch layer | Axiom 4 compliance; core Validity/Conditioning types; assignment via _validity() and _conditioning() helpers in source | empirical | medium — field assignments read from source and one direct test; no exhaustive parametric test across all 8 statuses × 5 validity fields |
| Source purity (no hidden guard rails, unidirectional dependency) | Pass two source-purity test checks: absence of forbidden tokens from branch source files; no import of lloyd_v4.branch from earlier-layer modules; math.isfinite and math.log are the only math module uses (scalar math for log-log slope computation); ProtocolViolationError for non-finite/non-positive inputs | Silently clamp or rescue non-finite inputs; note: math.log is direct stdlib usage, not derived through synthesis protocol (Axiom 11 concern — open interpretive question not resolved in tests) | tests/test_task006_source_purity.py (2 tests: token-based guard-rail audit; dependency-direction check) | branch parents = [core, primitives, projection, metrology]; layer_manifest.json enforces no upward dependency | proven | high |
| JSON serialisation of all branch outputs | All three TypedResult value types (SlopeFlowComparisonValue, KqSlopeStabilityValue, BranchFingerprintValue) implement to_json_safe() with no NaN/Infinity float sentinels; provenance parent chains preserved (trace IDs as strings); stable field names matching dataclass field names | Deserialise from JSON (to_json_safe is one-way); schema validation or versioning; fingerprint_components dict contains string values not typed result objects — consumers cannot reconstruct typed results from serialised fingerprint alone | tests/test_task006_serialization.py (1 test: json.dumps(allow_nan=False) for flow, kq, fingerprint results) | branch (parent: core, primitives, projection, metrology); serialisation via core.serialization.to_json_safe | proven | high — test explicitly exercises json.dumps(allow_nan=False) |
| SlopeFlowSample detection-status integration (metrology LOD interoperability) | SlopeFlowSample accepts optional detection_trace_id and detection_status fields; _is_loggable filter treats sample as usable only if detection_status is None or equals MetrologyStatus.DETECTED.value; BELOW_LIMIT_OF_DETECTION samples filtered out; allows metrology layer LOD results to be wired directly into slope-flow analysis | Automatically propagate detection metadata from metrology results into SlopeFlowSample (caller must manually copy); integrate NoiseFloorResult directly; handle MetrologyStatus.INDETERMINATE as a distinct usability state — samples with any status other than DETECTED are treated as non-loggable | tests/test_task006_slope_flow_direct.py (1 test: uses classify_against_noise_floor result, passes detection_trace_id and detection_status into SlopeFlowSample, verifies BELOW_LIMIT_OF_DETECTION causes filtering → SLOPE_FLOW_INSUFFICIENT_SAMPLES) | branch imports MetrologyStatus from lloyd_v4.core.status; interoperability is by convention not formal protocol | empirical | medium — one integration test; other MetrologyStatus values not explicitly tested in branch layer |

---

## L3a Refinery + History

**Authoritative status:** Partial; not authoritative. V4_GLOSSARY.md §3 table (line 120) explicitly states L3a Refinery/History = "Partial; not authoritative." CLAUDE.md §1: "Layer 3 (refinery/solver) is partial and not authoritative." The layer_manifest.json carries no explicit `status` or `authoritative` keys for refinery or history layers (absence is consistent with partial status). LIVE_CAMPAIGNS_LEDGER.md: `layer-3-promotion` campaign is active; Gates 2 and 3 are open as of 2026-05-26.

**Layer-manifest lineage note:** `refinery` parent = [core, primitives, projection, metrology, branch]; `history` parent = [core, primitives, projection, metrology, branch, refinery]. Refinery: 4 source files (~600 lines), 7 test files, 52 tests. History: 1 source file (status_trace.py, ~525 lines), 6 test files, 18 tests. The layer_manifest.json labels these "Layer 2 protocol-aware rewrite evaluation" (refinery) and "Layer 2 status-history evidence" (history) in prose — this refers to structural depth in the manifest DAG; V4_GLOSSARY §3 classifies them as L3a. Note: L3a does NOT cover Observer-layer (AlphaProbeStatus, SweepSignatureStatus, jet-bundle) snapshot geometry — the refinery snapshot falls back to a generic fingerprint for those types.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| snapshot_typed_result | Capture compact, serialisable TypedResultSnapshot from any V4 TypedResult; preserves protocol identity, status family, status string, validity dict, conditioning dict, value fingerprint (geometry keys vary by result type: ProjectiveRatioValue, StratifiedQuadraticRootValue, ProjectionResultValue, NoiseFloorValue, LimitOfDetectionValue, ProxyCalibrationValue, ValidProxyCalibrationValue, SlopeFlowComparisonValue, KqSlopeStabilityValue, BranchFingerprintValue); source_trace_ids (parents + value-specific supplemental trace IDs); rejects non-TypedResult and non-enum statuses with ProtocolViolationError | Snapshot Observer-layer (L1.5 observers/alpha_probe/sweep_signature/jet_bundle) results with typed geometry — falls back to generic {value_type: ClassName} fingerprint; snapshot solver-layer results with typed solver geometry; no round-trip deserialisation | tests/test_task007_refinery_snapshot.py: 6 tests (rejects raw inputs; projective_ratio shape/protocol/trace; quadratic_root branch_labels; projection branch/status/sources; metrology role/status; branch_fingerprint model/proxy/projection evidence) | refinery (parent: core+primitives+projection+metrology+branch); listed under Operations in layer_manifest.json | proven | high |
| compute_slag_vector / compare_slag_vectors / aggregate_slag_vectors | Compute SlagVector from TypedResultSnapshot against 8-dimension set (warning_count, refusal_count, indeterminate_count, incomplete_count, uncalibrated_count, unstable_count, max_model_residual, max_kq_slope_abs); unavailable dimensions recorded rather than filled with sentinels; compare two SlagVectors componentwise producing SlagComparison; aggregate a list of SlagVectors by summation | Slag dimensions are binary counts (0/1) except max_model_residual and max_kq_slope_abs; absent fingerprint keys → dimensions simply absent; no weighted or normalised comparison; no fractional slag for categorical dimensions | tests/test_task007_slag_gate.py: 5 tests; tests/test_task007_serialization.py: 2 tests | refinery (parent: core+primitives+projection+metrology+branch); Operations in layer_manifest.json | proven | high |
| compare_refinery_scenario | Compare reference vs candidate snapshots for single scenario; produce RefineryScenarioComparison with: protocol_match, status_family_match, status_match, validity_match, geometry_match, source_trace_preserved, SlagComparison; return one of 10 RefineryStatus strata; apply matching _STATUS_PRESERVATION_RULE for provenance | Observer-layer status families yield REWRITE_INDETERMINATE_UNHANDLED_STATUS; geometry matching does not handle AlphaProbeStatus, SweepSignatureStatus, etc. | tests/test_task007_same_geometry_checks.py: 10 tests covering all rejection branches for projective/quadratic/projection/fingerprint families plus unknown-family indeterminate | refinery (parent: core+primitives+projection+metrology+branch); Operations: compare_refinery_scenario | proven | high |
| evaluate_rewrite_candidate | Evaluate multi-scenario set of reference vs candidate snapshots; return RefineryDecisionResult; requires paired, non-empty, equal-count, unique-scenario-id sets; aggregate per-scenario SlagVectors via summation; accept if aggregate is strictly lower with no regressions; full provenance trace; serialisable to_json_safe | Partial-match fallback: any scenario-level rejection propagates to aggregate; no weighted scoring or per-dimension policy; no validation that declared_slag_dimensions are populated by provided snapshot types | tests/test_task007_slag_gate.py (5 tests); tests/test_task007_refinery_protocols.py (4 tests); tests/test_task030_refinery_mvp.py (22 tests, marked slow — evals-layer MVP) | refinery (parent: core+primitives+projection+metrology+branch); Operations: evaluate_rewrite_candidate | proven | high |
| require_accepted_rewrite | Protocol gate: return input RefineryDecisionResult unchanged if status is REWRITE_ACCEPTED_SAME_GEOMETRY_LOWER_SLAG; otherwise wrap in TypedRefusal with SCALARIZATION_REFUSED and defined=False; handle wrong status family gracefully | Re-evaluate the decision; distinguish indeterminate vs rejected-with-evidence refusals | tests/test_task007_refinery_protocols.py: test_require_accepted_rewrite_returns_typed_refusal_for_nonaccepted_statuses (all RefineryStatus strata); test_require_accepted_rewrite_fails_wrong_family_explicitly | refinery (parent: core+primitives+projection+metrology+branch); Operations: require_accepted_rewrite; REFINERY_REQUIRE_ACCEPTED_TRANSITION_RULE registered | proven | high |
| RefineryStatus strata (10 named values) | Define and enforce 10 typed strata: REWRITE_ACCEPTED_SAME_GEOMETRY_LOWER_SLAG, REWRITE_EQUIVALENT_NO_IMPROVEMENT, REWRITE_REJECTED_STATUS_FAMILY_MISMATCH, REWRITE_REJECTED_PROTOCOL_MISMATCH, REWRITE_REJECTED_STATUS_MISMATCH, REWRITE_REJECTED_VALIDITY_MISMATCH, REWRITE_REJECTED_GEOMETRY_MISMATCH, REWRITE_REJECTED_SLAG_REGRESSION, REWRITE_INDETERMINATE_INSUFFICIENT_EVIDENCE, REWRITE_INDETERMINATE_UNHANDLED_STATUS — V4_GLOSSARY §3 mentions 8 strata; source enumeration confirms 10 named values | Partial acceptance or graduated acceptance; stratum for 'geometry match but evidence inconclusive on slag direction' beyond the two INDETERMINATE variants | tests/test_task007_refinery_protocols.py, test_task007_transition_rules.py, test_task007_same_geometry_checks.py — all strata exercised | core status module (RefineryStatus defined in core/status); refinery layer provides and operates on it | proven | high |
| Status preservation transition rules (5 families) | Define 5 StatusTransitionRule instances: PROJECTIVE_RATIO, QUADRATIC_ROOT, PROJECTION, METROLOGY, BRANCH_FINGERPRINT _STATUS_PRESERVATION_TRANSITION_RULE; applied via apply_status_transition during compare_refinery_scenario for provenance | No preservation rule for Observer-layer families (AlphaProbeStatus, SweepSignatureStatus, ScalarAlphaJetBundleStatus, etc.) or HistoryStatus or SolverStatus → REWRITE_INDETERMINATE_UNHANDLED_STATUS | tests/test_task007_transition_rules.py: 3 tests including test_task007_status_preservation_rules_cover_each_family | refinery (parent: core+primitives+projection+metrology+branch); transition types in layer_manifest.json | proven | high |
| record_status_event | Record compact HistoryEventResult from any V4 TypedResult; captures: stream_id, observation_key, step_index (≥0 int), optional scenario_id and geometry_signature, source_protocol, source_status_family, source_status (string), source_validity, source_conditioning, source_trace_id, source_operation_id, source_expression_path, source_precision, source_backend, source_device; always emits HISTORY_EVENT_RECORDED; Provenance parents = (source_trace_id,) | Capture full value payload of the source result — only status-level metadata plus provenance fields; record events from non-TypedResult objects; auto-derive geometry_signature (caller-supplied opaque string) | tests/test_task008_history_event_recording.py: 3 tests (records all 6 status families; preserves protocol/validity/conditioning/source_metadata; rejects invalid inputs) | history (parent: core+primitives+projection+metrology+branch+refinery); Operations: record_status_event; HISTORY_RECORD_EVENT_TRANSITION_RULE registered | proven | high |
| compare_status_events | Compare two HistoryEventResults; classify transition as one of 7 HistoryStatus strata: HISTORY_TRANSITION_STABLE, PROTOCOL_CHANGED, STATUS_FAMILY_CHANGED, STATUS_CHANGED, VALIDITY_CHANGED, GEOMETRY_CHANGED, INCOMPARABLE; report changed_fields tuple | Detect skipped steps (caller-supplied ordering only); detect geometry change beyond geometry_signature string equality; aggregate diff across multiple transitions | tests/test_task008_status_transition_comparison.py: 3 tests | history (parent: core+primitives+projection+metrology+branch+refinery); Operations: compare_status_events; HISTORY_EVENT_PAIR_COMPARE_TRANSITION_RULE registered | proven | high |
| build_status_trace | Build HistoryTraceResult from ordered sequence of HistoryEventResults; strata: HISTORY_TRACE_EMPTY, SINGLETON, STABLE, TRANSITIONED, INCOMPLETE, UNORDERED; StatusTraceValue carries event_count, transition_count, stable bool, transition_status_counts dict, event_trace_ids, source_trace_ids, transition_trace_ids | Sort or repair unordered events — HISTORY_TRACE_UNORDERED is terminal; distinguish between partially-stable and fully-transitioned traces finer than single TRANSITIONED status; windowed or subrange trace building | tests/test_task008_status_trace_building.py: 3 tests | history (parent: core+primitives+projection+metrology+branch+refinery); calibrated_primitive_operations: build_status_trace; HISTORY_EVENTS_TO_TRACE_TRANSITION_RULE registered | proven | high |
| require_stable_status_trace | Protocol gate: return trace unchanged if status is HISTORY_TRACE_STABLE; otherwise wrap in TypedRefusal with SCALARIZATION_REFUSED and observable=True/defined=False; handle non-HistoryStatus gracefully | Force convergence; re-evaluate the trace; SINGLETON traces are refused (not stable); TRANSITIONED traces are refused even if all transitions are expected | tests/test_task008_history_protocols.py: 3 tests | history (parent: core+primitives+projection+metrology+branch+refinery); Operations: require_stable_status_trace; HISTORY_TRACE_REQUIRE_STABLE_TRANSITION_RULE registered | proven | high |
| HistoryStatus strata and protocols | Define EVENT_STATUSES (1), TRANSITION_STATUSES (7), TRACE_STATUSES (6); four protocols: HISTORY_EVENT_PROTOCOL, HISTORY_TRANSITION_PROTOCOL, HISTORY_TRACE_PROTOCOL, STABLE_HISTORY_TRACE_PROTOCOL | No HISTORY_TRANSITION_PROTOCOL consumer gate for specific transition kinds; no protocol for multi-stream or multi-key trace aggregates | tests/test_task008_history_protocols.py: 3 tests; tests/test_task008_transition_rules.py: 4 tests | history (parent: core+primitives+projection+metrology+branch+refinery); status_families: [HistoryStatus]; protocol types listed in layer_manifest.json | proven | high |
| Dependency isolation (source purity) | Mechanically enforce: earlier layers may not import from history; history terms may not appear in algorithm layers; refinery may not import from V3; forbidden identifiers banned across all source | Static text checks only — aliased or dynamically constructed imports would not be caught | tests/test_task007_source_purity.py: 3 tests; tests/test_task008_source_purity.py: 3 tests | Cross-layer constraint; enforced in test suite not manifest | proven | high |
| L3 promotion (layer-3-promotion campaign gates) | Campaign exists and is active; Gate 2 (multi-fixture refinery audit: repeat Task 031 six-candidate Pareto audit on Schwarzschild, SR, cbrt fixtures) and Gate 3 are open; Task 031 Sterbenz audit produced finding that sub-lattice alignment is a separate optimisation criterion from operation-level exactness | Gates 2 and 3 have not closed as of 2026-05-26 (last ledger update); refinery and history remain partial/non-authoritative; no substrate promotion executed; layer_manifest.json has no authoritative/status field for refinery or history | tests/test_task030_refinery_mvp.py (22 tests, slow — evals layer); tests/test_task031_sterbenz_audit.py; Build_Docs/Reports/task030_refinery_mvp/, task031_sterbenz_audit/, task032_cross_fixture_refinery_audit/ | LIVE_CAMPAIGNS_LEDGER.md layer-3-promotion campaign; V4_GLOSSARY.md §3 table row for L3a | open | high |

---

## L3b Solver

**Authoritative status:** Partial; not authoritative. V4_GLOSSARY.md §3 (line 121): "L3b Solver | Partial; not authoritative." CLAUDE.md §1 corroborates. LIVE_CAMPAIGNS_LEDGER.md `layer-3-promotion` campaign is the active path to promotion.

**Layer-manifest lineage note:** `solver` parent = [core, primitives, projection, metrology, branch, refinery, history]. Single implementation file: src/lloyd_v4/solver/typed_projection_solver.py (~622 lines). Status family: SolverStatus (14 values). Three protocol declarations. Six transition rules. 32 functional tests (12 test files) all passing; 2 source-purity tests fail but failures are entirely in evals/ not solver/.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| evaluate_solver_step | Given LocalQuadraticStepModel (quadratic coefficients a/b/c, state_before, branch label, residual_observable) plus noise-floor TypedResult and SolverPolicy: classify residual via metrology layer (IDENTITY_ZERO / BELOW_LIMIT_OF_DETECTION / DETECTED / DETECTION_INDETERMINATE); gate on optional branch-fingerprint and refinery-acceptance policy flags; run stratified_quadratic_roots + branch_selection + exact_quadratic_projection; map projection status to SolverStatus; return typed SolverStepResult with full provenance chain (residual-detection trace, root-state trace, projection trace, branch-fingerprint trace, refinery-decision trace) | Self-generate quadratic coefficients; perform multi-start, Halley-step, or higher-order correction; operate without declared noise floor; scalarize output (CONVERGED_SOLVER_PROTOCOL blocks scalarization); adaptive step-size control; regularisation, clamping, or hidden guard rails | tests/test_task009_solver_step_projection.py (5 tests); tests/test_task009_solver_convergence_metrology.py (5 tests); tests/test_task009a_metrology_policy_scenarios.py (1 test) — 11 tests total | solver (parent: core, primitives, projection, metrology, branch, refinery, history); calibrated_primitive_operations: evaluate_solver_step | empirical | high |
| run_typed_projection_solver | Accept Sequence[LocalQuadraticStepModel] with strictly ascending step_index and state continuity enforced, plus noise-floor result and SolverPolicy; iterate evaluate_solver_step per model; stop at first terminal status; accumulate projection events for SOLVER_STEP_ADVANCED steps; build status trace of projection geometry events; check for history stability if policy.require_stable_projection_history=True; return SolverRunResult with terminal SolverStatus, step_values, initial/final_state, terminal_step_index, projection_history_id; detect empty input (SOLVER_INDETERMINATE), duplicate model_ids (SOLVER_SEQUENCE_INCONSISTENT), out-of-order indices, and state discontinuity; emit SOLVER_STEP_BUDGET_EXHAUSTED on budget exhaustion | Restart from mid-sequence checkpoint; backtrack or try alternative branches; apply refinery-rewrite autonomously; adaptive budget; SOLVER_CONVERGED_IDENTITY and SOLVER_CONVERGED_BELOW_DETECTION only arise as individual step terminal statuses | tests/test_task009_solver_run_history.py (5 tests); tests/test_task009a_history_and_sequence_scenarios.py (2 tests) — 7 tests total | solver (parent: core, primitives, projection, metrology, branch, refinery, history); calibrated_primitive_operations: run_typed_projection_solver | empirical | high |
| require_converged_solver | Validate SolverRunResult against CONVERGED_SOLVER_PROTOCOL (accepts only SOLVER_CONVERGED_IDENTITY and SOLVER_CONVERGED_BELOW_DETECTION); return result unchanged if converged; otherwise wrap in protocol-refusal TypedResult with SCALARIZATION_REFUSED and original solver status, preserving value payload | Force convergence; re-run the solver; distinguish between IDENTITY and BELOW_DETECTION convergence beyond what CONVERGED_SOLVER_PROTOCOL captures | Covered transitively by run/step tests and tests/test_task009_transition_rules.py::test_require_converged_rule_accepts_only_converged_statuses (1 test); no dedicated require_converged_solver unit test file | solver (parent: core+...+history); operations (not calibrated_primitive_operation) | empirical | medium — logic is simple but only indirectly tested |
| SolverStatus strata (14 values) | Define and emit 14 distinct typed strata: SOLVER_STEP_ADVANCED, SOLVER_CONVERGED_IDENTITY, SOLVER_CONVERGED_BELOW_DETECTION, SOLVER_PROJECTION_BLOCKED, SOLVER_TANGENT_BLOCKED, SOLVER_SELECTION_REFUSED, SOLVER_BRANCH_UNIDENTIFIED, SOLVER_PROXY_UNCALIBRATED, SOLVER_REFINERY_REJECTED, SOLVER_HISTORY_UNSTABLE, SOLVER_SEQUENCE_INCONSISTENT, SOLVER_STEP_BUDGET_EXHAUSTED, SOLVER_PROTOCOL_REFUSED, SOLVER_INDETERMINATE; each maps to defined Validity vector; STEP_TERMINAL_STATUSES and RUN_STATUSES frozensets declared | Partial-convergence stratum; multi-dimensional convergence stratum; refinery-improved-but-not-converged stratum | tests/test_task009a_solver_status_coverage.py::test_every_solver_status_is_intentionally_produced (1 test — verifies all 14 strata reachable by at least one scenario) | solver (parent: core+...+history); status_families: [SolverStatus]; defined in src/lloyd_v4/core/status.py | complete | high |
| SolverPolicy configuration gate | Parameterise step evaluation via four boolean flags: accept_below_detection, require_branch_fingerprint, require_refinery_acceptance, require_stable_projection_history; default = {accept_below_detection: False, require_branch_fingerprint: False, require_refinery_acceptance: False, require_stable_projection_history: True} | Express partial fingerprint acceptance; configure step-budget limit; configure noise-floor strategy | tests/test_task009_solver_branch_and_refinery_gates.py (4 tests); tests/test_task009a_branch_refinery_gate_scenarios.py (2 tests); tests/test_task009_solver_convergence_metrology.py::test_below_detection_requires_explicit_policy_to_converge (1 test) — 7 tests | solver (parent: core+...+history); value_types: [SolverPolicy] | empirical | high — all four policy flags exercised |
| Transition rules (6 registered) | Provide 6 StatusTransitionRule objects: RESIDUAL_DETECTION_TO_SOLVER, PROJECTION_TO_SOLVER_STEP, BRANCH_FINGERPRINT_TO_SOLVER, REFINERY_TO_SOLVER, PROJECTION_HISTORY_TO_SOLVER, SOLVER_RUN_REQUIRE_CONVERGED _TRANSITION_RULE; each declares accepted/refused/mapped statuses explicitly — no hidden fallback | REFINERY_TO_SOLVER_TRANSITION_RULE accepts only REWRITE_ACCEPTED_SAME_GEOMETRY_LOWER_SLAG — all other RefineryStatus values map to SOLVER_REFINERY_REJECTED; no partial-rewrite acceptance path | tests/test_task009_transition_rules.py (3 tests); tests/test_task009a_transition_rule_coverage.py (1 test) — 4 tests | solver (parent: core+...+history); transition_types: [all 6 rules] | empirical | high |
| Protocol declarations (3 registered) | Declare 3 protocols: TYPED_PROJECTION_SOLVER_STEP_PROTOCOL (emits full SolverStatus family), TYPED_PROJECTION_SOLVER_RUN_PROTOCOL (emits RUN_STATUSES), CONVERGED_SOLVER_PROTOCOL (consumer, accepts only SOLVER_CONVERGED_IDENTITY and SOLVER_CONVERGED_BELOW_DETECTION, scalarization_allowed=False, required_validity_fields={defined, observable}) | Protocol for partial convergence or below-detection-only result; STEP and RUN protocols as consumer gates without wrapping | Covered transitively; no isolated protocol-contract test file for solver specifically | solver (parent: core+...+history); protocol_types: [all 3] | empirical | medium — correct function verified empirically but no dedicated protocol-contract test file |
| Provenance and serialization | SolverStepValue and SolverRunValue implement to_json_safe(); provenance records operation_id, expression_path, parents (trace IDs of residual-detection, root-state, projection, branch-fingerprint, refinery-decision results); note: SolverRunValue.to_json_safe() uses obfuscated string concatenation for field names to avoid literal matches in source-purity checks — cosmetic only, no runtime effect | Round-trip deserialisation; serialized form does not include status family metadata beyond status string value | tests/test_task009_solver_serialization.py (2 tests); tests/test_task009a_solver_serialization_regression.py (1 test) — 3 tests | solver (parent: core+...+history); value_types: [SolverStepValue, SolverRunValue] | empirical | high |
| LocalQuadraticStepModel construction validation | Validate at __post_init__: model_id is nonempty string; step_index is int (not bool); state_before/a/b/c/residual_observable are all finite floats; branch is one of {minus, plus, repeated, linear}; geometry_signature is nonempty if provided; raises ProtocolViolationError on violation | Validate geometric consistency between a/b/c and declared branch (no discriminant check); validate branch_fingerprint_result or refinery_decision_result provenance types at construction time | Covered implicitly in all step tests via fixture construction; no dedicated standalone validation test found | solver (parent: core+...+history); value_types: [LocalQuadraticStepModel] | empirical | medium — validation logic straightforward but not independently stress-tested |
| Source isolation / dependency direction | solver/ imports only from declared parents; no lower-layer module imports from solver/; test_task009_source_purity.py::test_solver_dependency_direction_and_leakage passes; solver/ module itself is purity-clean | Note: test_task009_source_purity.py::test_task009_source_audits fails (32 offenders) but all offenders are in src/lloyd_v4/evals/, not in src/lloyd_v4/solver/ | tests/test_task009_source_purity.py::test_solver_dependency_direction_and_leakage (1 test, passing) | solver (parent: core+...+history) per layer_manifest.json | proven | high |

---

## Eval Layer

**Authoritative status:** Eval-layer (not substrate). CAMPAIGN_DISCIPLINE.md defines the eval-layer concept explicitly: eval-layer code lives in src/lloyd_v4/evals/ and is NOT in the LAYER_MANIFEST. Observer operations (directional_alpha_probe, sweep_signature_probe, scalar_alpha_jet_bundle, singular_alpha_jet_bundle) are in the LAYER_MANIFEST as the `observers` layer (L1.5), parent = [core, primitives]; they are operationally authoritative as L1.5 per V4_GLOSSARY §3. The remaining eval capabilities (precision campaigns, four-form battery, path law discovery, refinery MVP, sterbenz audit, substrate-invariant-search phases A-I, route/operand search, mcg-geometry-first) are NOT in the LAYER_MANIFEST and are not substrate layers.

**Layer-manifest lineage note:** `observers` (L1.5) parent = [core, primitives]; listed in LAYER_MANIFEST.md as calibrated_primitive_operations. All evals in src/lloyd_v4/evals/ are eval-layer artifacts per CAMPAIGN_DISCIPLINE.md §rule-1. Three eval modules have no direct test-import coverage: multi_precision_campaign (top-level wrapper), schwarzschild_four_form_campaign (top-level wrapper), substrate_invariant_search_phase_i.

| Capability | Can do | Cannot do | Test backing | Manifest lineage | Status | Confidence |
|---|---|---|---|---|---|---|
| directional_alpha_probe (observers L1.5) | Sample finite-difference grid over a callable g; measure transfer-function exponent α via log-log slope; classify into 12 AlphaProbeStatus strata (ALPHA_REGULAR_INTEGER, ALPHA_FRACTIONAL_BRANCH, ALPHA_NEGATIVE_SINGULARITY, ALPHA_MODEL_AMBIGUOUS, ALPHA_MODEL_NO_MATCH, ALPHA_CANCELLATION_DOMINATED, ALPHA_INSUFFICIENT_DATA, ALPHA_DOMAIN_REFUSED, ALPHA_NONFINITE, ALPHA_INDETERMINATE, ALPHA_ZERO_BOUNDARY, ALPHA_UNSTABLE_WINDOW); emit typed AlphaProbeResult with validity/conditioning/provenance; support nested-window evidence and optional companion sweep_signature_probe call (task036); recover α to ~1e-10 precision on clean cases | Auto-promote measured α to substrate constant; classify REGULAR_INTEGER without caller-supplied declared_alpha_band (design constraint — refuses to round without explicit tolerance); observe below noise floor; extend observable region in near-boundary (Sterbenz) regime without finer substrate-compliant instrument; carry audit stamps for wrong_clean_emit_count without task037/V4_AUDIT_FRAMEWORK integration | tests/test_task018_directional_alpha_probe.py (24 tests); tests/test_task022_audit_tightening.py (7 tests); tests/test_task023b_alphaprobe_reliability.py (35 tests); tests/test_task035_source_purity.py (3); tests/test_task036_alpha_probe_sweep_signature_companion.py (5) — ~74 tests | observers layer (L1.5 per LAYER_MANIFEST.md): parent = [core, primitives]; calibrated primitive operation; GAP-009 relocated from primitives to observers | proven | high |
| sweep_signature_probe (observers L1.5) | Compose typed_finite_difference and typed_log_log_slope into low-sensitivity sweep screening instrument; emit SweepSignatureValue with cancellation_grade (1 - r_squared), drop_rate, raw transfer counts, nested LogLogSlopeObservation; classify into 7 SweepSignatureStatus strata (SWEEP_SIGNATURE_CLEAN, CANCELLATION_DOMINATED, HIGH_DROP_RATE, DEGENERATE_INPUT, INSUFFICIENT_DATA, NONFINITE, DOMAIN_REFUSED); consumer protocol accepts only SWEEP_SIGNATURE_CLEAN; callable as companion from directional_alpha_probe | Discriminate between genuine cancellation and formulation-burden without companion alpha_probe; substitute for directional_alpha_probe; floor_proximate primitive (deferred per LIVE_CAMPAIGNS_LEDGER sweep_signature_probe campaign); optional typed_log_log_slope residual-statistics extension (deferred) | tests/test_task035_sweep_signature_probe.py (10 tests); tests/test_task035_layer_manifest.py (1); tests/test_task035_source_purity.py (3); tests/test_task035_protocol_compatibility.py (3); tests/test_task035_transition_rules.py (3); tests/test_task035_serialization.py (2) — 22 tests | observers layer (L1.5): parent = [core, primitives]; calibrated primitive operation per LAYER_MANIFEST.md; Task 035 | proven | high |
| scalar_alpha_jet_bundle (observers L1.5) | Shift g to g_local(h) = g(x0+h) - g(x0) (local additive construction); delegate to directional_alpha_probe; classify into ScalarAlphaJetBundleStatus strata including SCALAR_JET_REGULAR_INTEGER_ALPHA, SCALAR_JET_FRACTIONAL_ALPHA_BRANCH, SCALAR_JET_NEGATIVE_ALPHA_SINGULARITY, SCALAR_JET_ALPHA_MODEL_REFUSED, SCALAR_JET_ALPHA_CANCELLATION_DOMINATED; return ScalarAlphaJetBundleResult with full provenance lineage; emit derivative_at_point if slope observed; appropriate for probing at non-singular points where f(x0) is finite | Observe singular region where |f(x0+h)| blows up (requires singular_alpha_jet_bundle); observe negative-α at branch (local additive construction tends to zero as h→0+ when f(x0) is finite) | tests/test_task019_scalar_alpha_jet_bundle.py (25 tests) | observers layer (L1.5): parent = [core, primitives]; calibrated primitive operation per LAYER_MANIFEST.md; Task 019 | proven | high |
| singular_alpha_jet_bundle (observers L1.5) | Probe singular-direct case: g_singular(h) = f(x0+h) without subtraction; observe singular region where |f(x0+h)| blows up; classify into SingularAlphaJetBundleStatus strata; empirically cleaner than scalar probe in negative-α regime (~1e-13 floor vs ~1e-11) because large-binade BACL gives bit-exact cancellation when |g(h)|→infinity | Probe non-singular points where additive construction is needed; wire as companion to directional_alpha_probe directly (companion is one-way alpha→sweep per task036 scope); multi-D extension | tests/test_task021_singular_alpha_jet_bundle.py (23 tests) | observers layer (L1.5): parent = [core, primitives]; calibrated primitive operation per LAYER_MANIFEST.md; Task 021 | proven | high |
| alpha_probe_sweep_signature_companion_call_pattern | One-way companion pattern: directional_alpha_probe optionally invokes sweep_signature_probe on same grid and attaches three optional fields to AlphaProbeObservation (companion_sweep_signature_observation, companion_sweep_signature_status, companion_sweep_signature_trace_id); calibrated on 16 GR photon-sphere cases; allows consumer disambiguation of ALPHA_UNSTABLE_WINDOW | Reverse call (sweep→alpha) to avoid cycles; add new AlphaProbeStatus cells or transition rules; automatically resolve all UNSTABLE_WINDOW cases (diagnostic only); task037 (sterbenz_audit pre-screen integration) not yet implemented | tests/test_task036_alpha_probe_sweep_signature_companion.py (5 tests); tests/test_task036_layer_manifest.py (1); tests/test_task036_source_purity.py (2); tests/test_task036_serialization.py (1) — 9 tests | observers layer (L1.5): enhancement to directional_alpha_probe and sweep_signature_probe; Task 036 | empirical | high |
| multi_precision_theorem2_campaign (precision sub-package) | Run Task 017c multi-precision instrument validation across four fixtures (schwarzschild, sr, pure_algebraic, cbrt_chain) and four computation paths (F1, F2, F3, F4) plus supplementary paths; measure b_k at float32, float64, and Decimal precisions (50/100/200 digits); linear fit with bootstrap CI on log(precision) vs log(b_k); emit subclaim verdicts and headline classification; R²=1.0 in regular region confirmed; detect out-of-scope-by-design cases; byte-stable outputs | Classify cbrt fixture at Decimal precisions (design exclusion); cover Sterbenz boundary regime (Q5 remains open at boundary); float128 on platforms where unavailable; directly promote b_k law into substrate without separate derivation gate | tests/test_task017b_multi_precision_instrument_model.py (8 tests); tests/test_task017c_multi_precision_theorem2.py (40 tests) — 48 tests | eval-layer (src/lloyd_v4/evals/precision/): not in LAYER_MANIFEST; eval-layer per CAMPAIGN_DISCIPLINE.md §rule-1 | proven | high |
| four_form_battery_campaigns | Implement four-form battery evaluation (F1, F2, F3, F4 and variants) for schwarzschild, SR, pure_algebraic, cbrt_chain, schwarzschild_quartic, schwarzschild_cbrt, pure_algebraic_quartic fixtures; lattice campaigns (integer-level grain); polarity grid stability comparisons; cross-fixture comparison; detect Sterbenz boundary directional bias; byte-stable JSON outputs; path_catalog, path_signature, path_clustering; cross-fixture closure analysis | Run without fixture-specific operand grids; promote new form status into substrate status families; F5+ form substrate definition (eval-layer candidates only); multi-dimensional fixtures within current four-form framework | tests/test_task024b_schwarzschild_four_form.py (9); test_task026_lattice_anomaly_investigation.py (13); test_task026c_prime_polarity_grid_stability.py (15); test_task027_sr_four_form_cross_fixture.py (16); test_task028_conditional_masks_joint_lattice_pure_algebraic.py (21); test_task029_path_basis_rank_clustering.py (25); test_task029b_methodology_refinement.py (20); test_task029c_cbrt_four_form_battery.py (29); test_task032_quartic_lattice_grain_discrimination.py (27); test_task033_schwarzschild_cbrt_transformed_n3.py (29); test_task034_schwarzschild_quartic_transformed_n4.py (30) — ~234 tests | eval-layer (src/lloyd_v4/evals/): not in LAYER_MANIFEST | proven | high |
| path_law_discovery | Discover candidate algebraic laws describing path-dependent residual envelope; build candidate term library (rational and irrational combinations of r/x); evaluate via sparse OLS with six validation axes (A: fit quality, B: precision-scaled residuals, C: oracle residuals, D: regional, E: zero-mask, F: sign-mask); rank fits by parsimony; produce PathEnvelopeLawValue with axis verdicts; includes rediscovery gate; covers schwarzschild, SR, pure_algebraic fixtures | Auto-promote discovered law to substrate theorem; use numpy in eval-layer is permitted (Axiom 11 governs substrate); discover laws for multi-D or cbrt fixtures within current candidate library | tests/test_task025_path_law_discovery.py (12 tests) | eval-layer (src/lloyd_v4/evals/): not in LAYER_MANIFEST | empirical | high |
| refinery_mvp (burden_vector + pareto_decision) | Implement Task 030 eval-layer F1-vs-F2 decision MVP for pure_algebraic fixture; extract 8-dimensional burden vector from committed JSON campaign reports; perform Pareto comparison between reference (F1) and candidate (F2) with configurable burden policy; check geometry admissibility; produce MvpDecisionRecord; read committed JSONs deterministically without re-running campaigns | Re-run campaigns (reads existing committed JSON only); generalize to multi-fixture Sterbenz audit; promote decision protocol to L3 substrate without separate gate | tests/test_task030_refinery_mvp.py (22 tests) | eval-layer (src/lloyd_v4/evals/refinery_mvp/): not in LAYER_MANIFEST; explicitly marked 'Not authoritative L3' in V4_GLOSSARY §9 | empirical | high |
| sterbenz_audit (rewrite candidate evaluation) | Enumerate six rewrite candidates (C1–C6) for Sterbenz boundary sub-expression; measure b_k, lattice grain, polarity summary for each at float32/float64/Decimal in Sterbenz and inapplicable regions; run N-way Pareto frontier computation; produce SterbenzAuditResult with burden vectors and frontier; discovered sub-lattice alignment as a finding; byte-stable outputs | Generalize to multi-fixture (next concrete step in layer-3-promotion, not yet implemented); promote any rewrite decision to substrate without separate gate; C6 (decimal_emulated) is reference-only, not substrate-admissible (Axiom 11) | tests/test_task031_sterbenz_audit.py (37 tests) | eval-layer (src/lloyd_v4/evals/sterbenz_audit/): not in LAYER_MANIFEST | empirical | high |
| substrate_invariant_search phases A-H | Nine eval-layer phases (A-H have 8 dedicated test functions each); probe candidate substrate observables (K_G, E = log2(|base_operand|), alpha, log-log slope) across fixtures; alpha-recovery characterisation (May 2026): 5 of 12 AlphaProbeStatus cells empirically observed; cross-fixture log-log slope agreement at branch: Schwarzschild 0.9962, pure_algebraic 1.0000, |Δ|=0.0038 at N=5; phase-chained JSON artifacts | Phase I has NO test file (zero test coverage); substrate-derivation of K_G remains open: Phase E Path A failed; Path B via BACL+α+slope not yet attempted; G empirically absent in 1D scope but not ruled out for multi-D; results are research-grade not audit-stamped | tests/test_substrate_invariant_search_phase_a.py through test_substrate_invariant_search_phase_h.py (8 tests each = 64 tests total); Phase I: none | eval-layer (src/lloyd_v4/evals/substrate_invariant_search_phase_*.py): not in LAYER_MANIFEST; active campaign per LIVE_CAMPAIGNS_LEDGER | empirical | high |
| substrate_invariant_search_phase_i (focused-probe sweep) | Module exists (src/lloyd_v4/evals/substrate_invariant_search_phase_i.py) with full implementation of triangulation and focused-probe sweep sub-phases | Zero test coverage — no test_substrate_invariant_search_phase_i.py found; no import of this module in any test file; cannot be considered validated output | none found | eval-layer (src/lloyd_v4/evals/): not in LAYER_MANIFEST; Phase I per pre-registry in Build_Docs/Agent_tasks/substrate_invariant_search_phase_i_focused_probe_sweep.md | open | low — zero test coverage |
| route/operand search evals (15 modules) | F2/F4 route-combination search via comb exhaustion; F1/F2 natural phase analysis; hard-cell Q-source exhaustion; dual-Q-source companion gap search; phase lock detection; early rounding comb utilization; controlled dither readback; route-bank offset guard audit; route-pair selection stability; inverse half-grid design audit; split-constant form search; integer-cell diagnostics; zero-offset transcendental Q-source search; all produce byte-stable JSON outputs | No campaign-level orchestrator; no promotion of route findings to substrate; most are single-fixture or fixture-class constrained; all cross-phase data flows through committed JSON files (no live cross-phase API) | tests for 15 modules: ~106 tests total across test_f2_operand_route_search.py, test_f4_route_comb_search.py, test_f2_phase_drift_diagnostics.py, test_f1_f2_natural_phase.py, test_hard_cell_q_source_exhaustion_search.py, test_dual_q_source_companion_gap_search.py, test_early_operand_phase_lock_search.py, test_early_rounding_comb_utilization.py, test_controlled_offset_dither_readback.py, test_route_bank_offset_guard_audit.py, test_route_pair_selection_stability_audit.py, test_inverse_half_grid_design_audit.py, test_split_constant_half_grid_form_search.py, test_split_constant_integer_cell_diagnostic.py, test_zero_offset_transcendental_q_source_search.py | eval-layer (src/lloyd_v4/evals/): not in LAYER_MANIFEST | empirical | high |
| mcg_geometry_first campaign evals (9 modules) | Geometry table generation with finite-difference backend metadata; readback table with phase-separation classification; C-profile; C-def-1 calibration artifact with source SHA256 hashes for 7 prior artifacts; E-reducibility analysis; uniform grid for pure_algebraic; solve-for-scout relation families; V3 diagnostic bridge artifact (Phase 2h, descriptive mapping only: direct_analogue / diagnostic_neighbour / oracle_crosscheck_only / not_supported / not_applicable_in_1d); fixture-class separation strictly enforced | V3 bridge is descriptive mapping only — Vera/V3 vocabulary cannot be promoted into V4 substrate (Axiom 10); G candidates not promoted from any phase; multi-D extension not implemented; solve_for_scout artifact generation does not itself derive substrate primitives | tests/test_mcg_geometry_first_geometry.py (7); test_mcg_geometry_first_readback.py (10); test_mcg_geometry_first_c_profile.py (9); test_mcg_geometry_first_cdef1_calibration.py (8); test_mcg_geometry_first_e_reducibility.py (11); test_mcg_geometry_first_grid_stability.py (9); test_mcg_geometry_first_pa_e_uniform_grid.py (12); test_mcg_geometry_first_solve_for_scout.py (11); test_mcg_geometry_first_v3_bridge.py (10) — 87 tests | eval-layer (src/lloyd_v4/evals/mcg_geometry_first_*.py): not in LAYER_MANIFEST; merged into substrate-invariant-search per LIVE_CAMPAIGNS_LEDGER | empirical | high |
| multi_precision_campaign (top-level wrapper) | Top-level src/lloyd_v4/evals/multi_precision_campaign.py imports from precision sub-package and orchestrates artifact generation | No direct test-import coverage; tests/test_task017c_multi_precision_theorem2.py covers lloyd_v4.evals.precision.multi_precision_campaign (sub-package, 40 tests) — the top-level wrapper has no independent test coverage | none found (direct module import); sub-package: 40 tests | eval-layer (src/lloyd_v4/evals/multi_precision_campaign.py): not in LAYER_MANIFEST; distinct from precision sub-package | partial | medium — sub-package well tested; top-level wrapper untested |
| schwarzschild_four_form_campaign (top-level wrapper) | Top-level eval module wrapping the Schwarzschild four-form campaign run; imports core sub-modules; provides campaign runner and byte-stable artifact generation | No direct test-import coverage; tests/test_task024b_schwarzschild_four_form.py (9 tests) covers underlying schwarzschild_four_form module, not the top-level campaign wrapper | none found (direct module import); underlying module: 9 tests | eval-layer (src/lloyd_v4/evals/schwarzschild_four_form_campaign.py): not in LAYER_MANIFEST | partial | medium |
| eval-layer campaign discipline and byte-stable output infrastructure | Every eval module follows CAMPAIGN_DISCIPLINE.md pattern: run_campaign() → dict, write_campaign_output(path) → dict, campaign_bytes(payload?) → bytes; all outputs byte-stable (regenerate and diff before claiming a change); JSON serialization via lloyd_v4.core.serialization.to_json_safe; campaign outputs committed to Build_Docs/Reports/ directories; each eval phase reads prior phases via committed JSON artifacts | Unified eval orchestrator or DAG runner; live cross-phase API (all cross-phase data flows through committed JSON files); substrate promotion without separate derivation gate; audit stamps without audit framework extension (V4_AUDIT_FRAMEWORK.md, blocked by Task 1 for transfer-observable-based campaigns); evals are not in the LAYER_MANIFEST — not substrate layers | Pattern verified across all 11+ campaign task test suites | eval-layer: explicitly stated in Build_Docs/CAMPAIGN_DISCIPLINE.md; not in LAYER_MANIFEST | proven | high |

---

## Gaps / Not-Yet-Built (aggregate)

The following gaps are identified across all layers. All claims are sourced from the capability tables above; confidence levels are inherited from those entries.

### L1 Primitives — Open Gaps

| Gap ID | Name | Blocker | Confidence |
|---|---|---|---|
| GAP-001 | typed_sqrt | GAP-009 L1 atomicity policy resolution required before Transplant 3 | high |
| GAP-002 | typed_log | GAP-009 L1 atomicity policy resolution (same constraint) | high |
| GAP-004 | typed_bacl_grain | GAP-009 resolution; depends on typed_ulp (resolved as GAP-003) | high |

### L0 Core — Partial / Known Issues

| Item | Description | Confidence |
|---|---|---|
| V3 isolation guard failure | src/lloyd_v4/evals/substrate_invariant_search_phase_e.py references lloyd_v3; test_task000_no_v3_dependency.py has 1 failing test; core/ module itself is clean | high |
| DETECTED_NONZERO (MetrologyStatus) | Declared in the enum (core/status.py) but not emitted by any operation in L2 metrology; unreachable from current metrology operations | high |
| policy-accepted validity field | Not a named field in the current Validity implementation (Axiom 4 names 5 fields; CLAUDE.md §4 mentions policy-accepted as a 6th validity concept but it is absent from the Validity dataclass) | high |
| Status calculus utilities — no dedicated tests | join_statuses(), propagate_invalid(), require_handled_status(), require_protocol_ok() are exercised only indirectly through upper layers; no dedicated test file | medium |
| refused_statuses not checked in validate_protocol | ConsumerProtocol.refused_statuses field is defined but not checked inside validate_protocol — only accepted_statuses is checked | high |

### L1.5 Projection — Minor Gaps

| Item | Description | Confidence |
|---|---|---|
| Scalarization gate — no dedicated test | scalarization_allowed=False on EXACT_QUADRATIC_PROJECTION_PROTOCOL and BRANCH_SELECTION_CONSUMER_PROTOCOL is enforced structurally but has no dedicated test for the gate specifically | medium |

### L2 Metrology — Partial Gap

| Item | Description | Confidence |
|---|---|---|
| estimate_bk_noise_floor — single method only | Only 'max_abs_observed' implemented; 'median', 'quantile', 'mean', 'percentile' all raise ProtocolViolationError | high |
| DETECTED_NONZERO — emitter absent | Status exists in MetrologyStatus enum but no operation emits it | high |

### L2 Branch — Coverage Gaps

| Item | Description | Confidence |
|---|---|---|
| Validity-field exhaustive parametric test absent | No test that checks all 8 branch statuses × 5 validity fields; one direct test exists (SLOPE_FLOW_OBSERVED); remaining fields are derivable from source but not independently tested | medium |
| SLOPE_FLOW_PROXY_UNCALIBRATED — internal emission absent | Declared in SLOPE_FLOW_STATUSES frozenset but not internally emitted by compare_slope_flow_to_models; reserved for upstream callers | high |
| math.log usage (Axiom 11 interpretive open question) | slope_flow.py lines 244-245 use direct math.log for log-log slope segment computation; whether this raises an Axiom 11 concern is not resolved by the test suite | medium |

### L3a Refinery + History — Structural Gaps

| Item | Description | Confidence |
|---|---|---|
| Observer-layer snapshot geometry | snapshot_typed_result falls back to generic {value_type: ClassName} fingerprint for AlphaProbeStatus, SweepSignatureStatus, ScalarAlphaJetBundleStatus, SingularAlphaJetBundleStatus — typed geometry evidence is lost | high |
| No preservation rule for Observer-layer families | Missing preservation rule → REWRITE_INDETERMINATE_UNHANDLED_STATUS outcome in compare_refinery_scenario | high |
| No round-trip deserialisation | to_json_safe is one-way for all L3a output types | high |
| layer-3-promotion Gates 2 and 3 open | Gates 2 and 3 not closed as of 2026-05-26 (last ledger update); refinery and history remain partial/non-authoritative | high |

### L3b Solver — Coverage Gaps

| Item | Description | Confidence |
|---|---|---|
| require_converged_solver — no dedicated unit test | Logic is simple but only covered transitively + one transition-rule test | medium |
| Protocol declarations — no dedicated protocol-contract test file | No isolated protocol-contract test file for solver (contrast with earlier layers that have dedicated test_taskXXX_protocols.py files) | medium |
| LocalQuadraticStepModel — no standalone validation test | Validation logic (ProtocolViolationError paths) not independently stress-tested | medium |

### Eval Layer — Untested / Partial Modules

| Module | Issue | Confidence |
|---|---|---|
| substrate_invariant_search_phase_i | Zero test coverage; module exists but is unvalidated | low |
| multi_precision_campaign (top-level) | No direct test-import coverage; only the precision sub-package version is tested | medium |
| schwarzschild_four_form_campaign (top-level) | No direct test-import coverage; only the underlying schwarzschild_four_form module is tested | medium |
| evals source purity — active V3 reference | test_task009_source_purity.py::test_task009_source_audits fails (32 offenders all in evals/); substrate_invariant_search_phase_e.py references lloyd_v3 | high |
| substrate_invariant_search Phase I / K_G Path B | K_G derivation via BACL+α+slope not yet attempted; Phase E Path A failed; substrate-derivation of K_G remains open | high |
