# Arc 03 — Four-form battery & cross-fixture invariance (Tasks 024b-029)
_Window: 2026-05-12 to 2026-05-13 (task024b May 12 00:03; task027 May 12 23:10; task028 May 13 00:00; task029 May 13 00:46). Confidence: high · read-only audit frame_

## 1. What the arc set out to build

The arc's intent is pre-registered task-by-task in the Codex specs under `Build_Docs/Agent_tasks/Completed/` and consolidated retrospectively in the arc-closing handoff `Docs/session_handoff_v4_substrate.md` (May 13 08:09, HEAD `8a62d32 Task 029`). It is the first arc to point the now-honest typed substrate (Arcs 01–02) directly at Will's actual phenomenon — the two-form GR/SR constraint pair from `where_i_got_stuck.md` — rather than at abstract alpha test-functions.

**The stated goal, in the arc's own words:** Run a "V4-native typed-substrate discovery campaign on V3's four-form Schwarzschild battery" (`codex_task024b_*.md` L24-37). The four forms are four algebraically-identical-to-zero rewrites of the same √(1−2/r) constraint: F₁ = R²−(1−2/r) (squared, subtraction), F₂ = R²−1+2/r (squared, reordered), F₃ = R−√(1−2/r) (sqrt, same path), F₄ = R−√((r−2)/r) (sqrt, different path), with R := √(1−2/r) evaluated once (`codex_task024b_*.md` L38-55). The spec is explicit that this is the V4 re-investigation of V3 Experiment 2, "**not** a replication of V3's slope" — V3's −0.4988 is "mechanical-property reference evidence that the design problem is real," and V4 "must arrive at its own observations through V4 primitives" (`codex_task024b_*.md` L31-37). Confidence: high.

**The arc's central question, stated at task 027:** "test whether the observed four-form signatures behave like an arithmetic-chain property across fixtures or change qualitatively with the fixture" (`task027_summary.md` L7-9). This is the **chain-property hypothesis** — the load-bearing object of the whole arc: are F₁–F₄'s residual signatures a property of the arithmetic chain (substrate), or of the specific physics fixture? Confidence: high.

**The pre-registered escalation ladder** (forward-references chained across summaries, each task gating the next): 024b establish the Schwarzschild battery → 025 search a fixed 17-term law library → 026/026c-prime characterise the lattice/anomaly and polarity structure → 027 add a **second physics fixture** (SR time-dilation) and run cross-fixture comparison → 028 add a **physics-stripped pure-algebraic control** to decide substrate-vs-fixture → 029 ask whether F₁–F₄ form a complete elementary-rewrite basis (`task027_summary.md` L130-134; `task028_summary.md` L206-212; `task029_summary.md` L185-190). Confidence: high.

**Discipline pre-registered as code, not prose** (`session_handoff_v4_substrate.md` L262-283): F3 sentinel (must stay exactly zero everywhere — halt loudly if it fires); F1/F4 negative control (must aggregate to depolarized/underpowered); F2/F4 bottle-cap (cannot promote without cofire ≥ 10 on all grids); byte-stable JSON verified by /tmp diff; **no new primitives, no status families, no manifest changes** — every task is an `evals/`-layer observation campaign only. Confidence: high.

## 2. Did it accomplish that?

**Verdict: delivered.** Every pre-registered task landed, test-green, byte-stable, with the headline finding the arc was built to test arriving as `chain_property_supported`. Confidence: high.

- **024b — Schwarzschild battery established.** Suite 414→423 (+9 tests), no src primitives/manifest touched. Emitted the predicted stratum pattern: F3 exactly silent (137 transfers all `0.0`, the calibration zero), F1 `alpha_unstable_window`, F2 `alpha_zero_boundary`, F4 structured non-zero with V3-overlay ratio median 1.0176 against `δf/(2√f)` — but V4 emitted its own typed strata rather than V3's slope (`task024b_summary.md` L14-16, L34-50, L96-101, L117-129). All 137 rows validated against the V3 reference overlay to within 1 ulp_f (L97-101). Confidence: high.
- **025 — law-library discovery.** F4 rediscovery gate passed (T_15 `δf/(2√f)`, R²=0.958); F1/F2 honestly classified `path_law_supported_envelope` (R²<0.30, no closed form claimed); F3 `path_law_exact_zero` all six axes (`task025_summary.md` L36-67). Confidence: high.
- **026 / 026c-prime — lattice and polarity structure.** 026 surfaced the headline F2 anomaly: F2 sits on **half-level (0.5) offsets** of ulp(f), classified `lattice_mismatch` not integer-lattice; F4 spread fully explained by integer-level quantisation (median ratio 2²⁹), 68/68 within factor 2 (`task026_summary.md` L42-81). 026c-prime confirmed **F1∥F2 grid-stable parallel polarity** across four independent r-grids (signs agree 100% where both fire; reference 16/16, p=3.1e-5), F1/F4 `depolarized_invariant` (negative control passed), F2/F4 `open_underpowered` (bottle-cap held) (`task026c_prime_summary.md` L50-95). Confidence: high.
- **027 — SR fixture + cross-fixture comparison.** SR preserved F1∥F2 grid-stable polarity, F3 silence, F2 non-integer lattice, F4 integer lattice, and the Sterbenz directional bias at the shifted boundary β=1/√2 (below density 0.896 vs above 0.220). Headline: `chain_property_partial` — strongest signatures preserved, diverged on negative-control power and F4 lattice grain (`task027_summary.md` L40-104). Codex self-caught and fixed an F1/F2 routing-order bug before recording (L113-114). Confidence: high.
- **028 — pure-algebraic control → the decision.** A physics-stripped four-form (operand with no fixture semantics, F4 split-routing `(1−x/2)−x/2`) reproduced all five invariants. Headline upgraded to **`chain_property_supported`**: all three fixtures agree on F1∥F2 grid-stable polarity, F3 silence, F2 non-integer lattice, F4 integer lattice, and predicted Sterbenz side — so the pattern is "an arithmetic-chain property rather than a fixture-specific property" (`task028_summary.md` L155-186). Suite 487→508. Confidence: high.
- **029 — basis-rank exploration → a real open frontier.** Built a 15-path elementary-rewrite catalog (7 rewrite classes), 6-D path signatures, pure-stdlib single-linkage clustering. Methodology gate held (F1–F4 in distinct clusters in every fixture). Headline `basis_rank_divergent`: at cut 0.10 rank is Schwarzschild 8 / SR 9 / pure-algebraic 8 — **F1–F4 is NOT the complete elementary-rewrite basis**; F5+ candidates appear in every fixture (`task029_summary.md` L155-176). Suite 508→533. Confidence: high.

**Net:** the arc delivered the **five-for-five substrate invariants** (F1∥F2 grid-stable polarity; F3 identity silence; F2 non-integer lattice grain; F4 integer lattice; Sterbenz boundary directional bias at a calculably-shifted location) corroborated across three independent fixtures, plus one derivable secondary mechanism (the Sterbenz boundary, derived from Sterbenz's Lemma applied to F2's R²−1 subtraction), and an honestly-flagged open frontier (basis_rank_divergent) (`session_handoff_v4_substrate.md` L63-123). Test count climbed monotonically 414→423→…→533 with no manifest mutation across 026–029, corroborating the observation-only discipline. Git commit dates (667d16d…8a62d32, all May 12–13) and report-body dates agree with file mtimes, so the within-arc ordering is firmly established. Confidence: high.

**Qualifier (not a failure):** the arc explicitly *withheld* substrate promotion. F1∥F2 polarity and the path-signature observable are flagged as promotion candidates only — promotion gated on (1) chain-property fully supported (✓) AND (2) "joint-state reveals derivable law (NOT yet — descriptive only)" (`session_handoff_v4_substrate.md` L161-167). This is pre-registered restraint, consistent with the "no designing ahead of evidence" discipline, not an unmet goal.

## 3. Project state at completion

By May 13 (HEAD `8a62d32 Task 029`, 533 tests passing), the engine was the same layered typed kernel as Arcs 01–02 — **no substrate growth this arc** — but with a new, populated `evals/` layer carrying the phenomenon campaign (`session_handoff_v4_substrate.md` L27-34). Confidence: high.

**Layers present (unchanged from Arc 02):** L0 core (TypedResult, Validity, Conditioning, Provenance with SHA-256 trace_id, protocols, status calculus, transitions, errors); L1 primitives (projective_ratio, stratified_quadratic_roots, typed_finite_difference, directional_alpha_probe, scalar + singular alpha-jet bundles, typed_log_log_slope); L1.5 projection (exact_quadratic_projection); L2/L3 metrology/branch/refinery/history/solver as **V3-shape deferred-consumer drafts, explicitly NOT authoritative** (`session_handoff_v4_substrate.md` L28-33). Confidence: high.

**What the engine could now do that it could not before this arc:** run a full four-form (F₁/F₂/F₃/F₄) residual campaign on Will's *actual* GR/SR constraint pair across float32/float64/decimal-50; reconstruct the Schwarzschild and SR fixtures plus a physics-stripped algebraic control from formulas under V4 arithmetic; read out per-form ULP-lattice classification (integer / non-integer / empty), signed-lattice histograms, conditional co-fire masks, parallel-polarity coupling with grid-stability gating, the Sterbenz boundary directional-bias prediction, and a 6-D path-signature clustering. Crucially, it could now distinguish a **substrate (arithmetic-chain) property from a fixture-specific physics property** by cross-fixture agreement — the first time the engine touched Will's phenomenon at all. Confidence: high.

**What it still could NOT do (open / blocked):** no multi-precision *execution* of `typed_finite_difference` for the precision-scaling law (Task 017b explicitly **banked**, `session_handoff_v4_substrate.md` L155-159) — so Obs7's lawful precision-ratio remained unattacked at the substrate level; no derivable joint-state law (the structure was still descriptive, blocking substrate promotion of any polarity/path-signature observable, L161-167); no operation-level Sterbenz annotation (Task 030, forward, L149-154); the **METHOD** Will lacked — a measurement that gets under the arithmetic noise floor and is trustworthy enough to separate real-vs-artefact (Q5/Q6) — still did not exist; F1–F4 known to be an incomplete rewrite basis (029) with the F5+ structure uncharacterised. Confidence: high.

**Then-active direction:** the "lens framing" introduced by the user during the 027 transition — "different fixtures are different lenses on the same substrate property; their divergences are about which regimes each lens powers up, not about the substrate disagreeing with itself" (`session_handoff_v4_substrate.md` L208-221) — plus a drafted-but-unexecuted Task 029b (methodology refinement: scale-invariant lattice metric to test whether P_scaled_* are metric artefacts) (L127-145). The handoff's stated default was "pause; ask what they want" — the substrate had "crossed from 'is this real' to 'what is this'" (L368-372). Confidence: high.

## 4. North-star distance

**Classification: advancing (with one strongly on-vector strand).** This is the arc that finally turns the engine onto Will's actual phenomenon, making concrete down-payments on Obs1/Obs4 (route matters), Obs6 (boundary amplitude), and Q2 (why route matters) — but it deliberately does not yet reach Q5 (the question that stops him) or Obs7, and it does not yet recover the doubling ladder (Obs3/Q3). Confidence: high.

**On-vector strand — route/path matters (Obs1, Obs4, Q2).** The north star's Obs1 is "two algebraically-identical forms behave completely differently — one identically zero, the other nonzero on ~half the points" and Obs4 is "the silent form is silent because of the arithmetic PATH, not because the physics is trivial." This arc *is* that observation, generalised and made typed: F3 (same arithmetic path as R) identically silent across every cell/precision/fixture while F1/F2/F4 carry structured residuals, and the residuals are a property of the **arithmetic chain** (proven by the pure-algebraic control reproducing them with the physics stripped out) — `task028_summary.md` L155-186 directly answers "is the route or the physics responsible: the route." The Sterbenz mechanism (F2's R²−1 subtraction being exact above a calculable boundary, `session_handoff_v4_substrate.md` L82-91) is a *derived* answer to "what property of a path selects which rounding survives" (Q2) and characterises one component of the boundary envelope (Obs6/Q4) — though the handoff is careful that Sterbenz is "one component, not whole of b_k" (L356). Confidence: high.

**Advancing, not yet arrived — the hard questions stay open by design.** Obs3/Q3 (the doubling ladder, factor-of-two rung spacing — Will's most confident observation) is *not* recovered in this arc; the lattice work finds half-integer (F2) and integer (F4) ulp grains, which is adjacent to but not the doubling ladder. Obs7/Q5 (lawful precision-scaling; real-vs-artefact) is explicitly deferred: multi-precision execution is banked as Task 017b (`session_handoff_v4_substrate.md` L155-159), and substrate promotion is withheld pending a derivable law (L161-167). So the arc advances the phenomenon axes (Obs1/4/6, Q2/partial-Q4) substantially while honestly leaving Q3, Q5, Q6, and Obs7 untouched — correct sequencing, not divergence. Confidence: high.

**Divergence-watch (flagged, not yet realised).** Two drift risks the record itself names: (a) the **Kerr leap** — "the floating-point grid is natively simulating Kerr" — fired during 026c-prime and was *retired correctly* by the user as physics-overreach; the arc-closing handoff installs it as a standing drift-pattern warning (`session_handoff_v4_substrate.md` L195-201). The output-discipline line held: no physics-interpretive language in task prose (L274-276). (b) The **paper** strand (Arc 04) begins consuming this arc's evidence into the transfer-function exponent-family draft (L52-60) — the adversary should watch whether the paper's "cross-fixture invariance theorem" is presented as derived when the arc itself labels it *empirical* (`chain_property_supported`, three fixtures, no derivation of the joint-state law). The arc-internal framing stays honest (descriptive, promotion withheld); the risk is downstream over-claiming. Adversary test: if any of (Obs3 doubling-ladder recovery, Obs7 precision-scaling execution, a *derived* cross-fixture law) appeared *inside* the 024b–029 window, the "advancing-not-arrived" call would be wrong — none found across all seven summaries, the 024b spec, or the closing handoff; 017b is explicitly banked and promotion explicitly withheld. Confidence: high.

## Adversarial check (independent refutation attempt)

_Read-only skeptic pass, 2026-05-30. Method: re-derived the in-window git chain (`667d16d`..`8a62d32`), read every 024b-029 summary plus 017b/017c/029b/029c, cross-checked the closing handoff line references. The two claims under test are the §2 deliver verdict ("delivered") and the §4 north-star call ("advancing"). Both claims appended verbatim; nothing above this line was altered._

### Claim (a) — DELIVER = "delivered"

**Refutation attempted, three angles.**

1. *Did every pre-registered 024b-029 task actually land test-green / byte-stable / observation-only?* I read all seven summaries (024b, 025, 026, 026c-prime, 027, 028, 029) and the closing handoff. Every one records the post-task suite passing, a byte-stable `/tmp` diff, and an explicit "no primitives / no status families / no manifest entry / no transition rule" line; 026-029 each re-assert `layer_manifest.json` unchanged. The headline arrives exactly as stated: 028 `chain_property_supported` (`task028_summary.md` L180-186), 025 F4 rediscovery gate R²=0.958 (`task025_summary.md` L44-49), 026 F2 half-level / F4 integer-quantised (`task026_summary.md` L41-81), 026c-prime F1∥F2 four-grid stability with F1/F4 negative control and F2/F4 bottle-cap (`task026c_prime_summary.md` L88-94), 027 `chain_property_partial` (`task027_summary.md` L96-104), 029 `basis_rank_divergent` (`task029_summary.md` L155-176). Codex's self-caught F1/F2 routing bug is recorded (`task027_summary.md` L113). **This angle fails to refute** — the delivery is fully corroborated.

2. *Is the test-count chain actually monotonic as stated ("414->423 (024b)->...->533 (029)")?* The real in-window chain is 414 → **423** (024b) → **431** (017b) → **443** (025) → **456** (026) → **471** (026c-prime) → **487** (027) → **508** (028) → **533** (029). It is monotonic (non-decreasing) and corroborates build order, so the headline number is not wrong. **This angle fails to refute the verdict** — but it surfaces a factual error that is load-bearing for claim (b): the chain the deliver claim renders as "424b->...->533" silently steps over an executed in-window task — **Task 017b** (commit `e598e6e`, 2026-05-12 10:09, baseline "post-024b, 423 tests" per `codex_task017b_*.md` L9-15), which the same claim elsewhere calls "banked."

3. *Was anything pre-registered that did NOT land?* The 024b spec, the escalation ladder, and the F3-sentinel / negative-control / bottle-cap discipline gates all landed. Substrate promotion was pre-registered as *withheld pending a derivable joint-state law* (`session_handoff_v4_substrate.md` L161-167), so its non-occurrence is restraint, not a miss. **This angle fails to refute.**

**Verdict on (a): STANDS.** Confidence: high. Every 024b-029 task delivered as pre-registered; if anything the arc *over*-delivered (017b also landed in-window). The only defect found is a framing error in the claim's own narration of the test-count chain — it omits the in-window 017b it calls "banked" — but that defect does not weaken "delivered."

### Claim (b) — NORTH-STAR = "advancing (Obs7/Q5 deliberately deferred, 017b banked, promotion withheld; no Obs3/Obs7/derived-law in window)"

**Refutation attempted, against the claim's own explicit adversary test.** The claim stakes itself on: *"if any of (Obs3 doubling-ladder recovery, **Obs7 precision-scaling execution**, a derived cross-fixture law) appeared inside the 024b-029 window, the 'advancing-not-arrived' call would be wrong — none found ... 017b is explicitly banked."* I tested each trigger:

- **Obs3 (doubling ladder):** not recovered in-window. No ladder/rung/doubling language in any 024b-029 or 017b summary (grep confirmed; the lattice work finds half-integer F2 and integer F4 grain, which is adjacent but not the factor-of-two rung ladder). The claim is correct here.
- **Derived cross-fixture law:** none. The cross-fixture finding is `chain_property_supported` — empirical across three fixtures, joint-state law explicitly *not* derived (`task028_summary.md` L211-212; handoff L161-167). The claim is correct here.
- **Obs7 (precision-scaling execution):** **PRESENT IN-WINDOW.** Task 017b — "Multi-Precision Confirmation of the IEEE 754 Instrument Model," committed `e598e6e` 2026-05-12 10:09:15, baseline post-024b (423 tests), squarely between 024b (`667d16d`, 05-12 00:05) and 025 (`0a2e068`, 05-12 11:41) — ran the four-form battery at float32 and float64 and recorded, Phase B: median `abs(F4_float32 / F4_float64) = 536870912.0 = 2²⁹`, expected binary unit ratio `536870912.0`, **observed/expected = 1.0, Phase B pass** (`task017b_summary.md` L57-64; spec `codex_task017b_*.md` L33-39). Set against Obs7 verbatim — "I ran the same route at one precision and then at a higher precision ... they scaled by what looked like an exact ratio between the two precisions — observed-against-expected sitting right on top of each other" — this is a direct, in-window empirical hit on the one observation Will called "the single fact that convinced me there is something real here." **The claim's third trigger fired. Its self-declared adversary test does not hold.**

**Source of the error — a naming collision the claim conflates.** There are two distinct objects both called "017b": (i) the *executed* "017b Multi-Precision Instrument Model" (in-window, May 12, did the float32/float64 ratio = Obs7 down-payment); and (ii) the "017b (banked)" of the handoff (L155-159), described as the *Theorem-2* multi-precision fit ("execute `typed_finite_difference` at numpy float32/64/**128** + decimal at varying contexts, fit C_p,k vs u_p"), which was actually executed later as **Task 017c** (`task017c_summary.md`, 2026-05-13 14:01, out of window, headline `theorem2_partial`). The claim treats Obs7 as wholly "banked / unattacked at the substrate level / deferred," reading only the handoff's (ii) and missing the in-window (i).

**Does the firing trigger move the classification from "advancing" to "arrived"?** No. 017b Phase B is a single-axis float32/float64 magnitude-ratio confirmation on one form (F4), one fixture (Schwarzschild); its own campaign headline is `model_supported = false` (Phase A's declared bound failed), and it explicitly defers the real Theorem-2 fit. Q5 (real-vs-artefact) and Q6 (the METHOD) remain untouched, and the full multi-precision separation (017c, `theorem2_partial`) only lands later and only partly. So the *coarse* call "advancing, not arrived" remains defensible on the merits.

**But the claim is not refuted by being too pessimistic; it is refuted by being factually wrong on a load-bearing point and by failing its own stated falsifier.** As written, claim (b) asserts (1) "Obs7 ... multi-precision execution banked as 017b," (2) "Obs7's lawful precision-ratio remained unattacked at the substrate level," (3) "no Obs7 precision-scaling execution appeared inside the window," and (4) "017b is explicitly banked." All four are false against the record: 017b *executed* in-window and *did* make a concrete Obs7 down-payment (the exact 2²⁹ ratio). The claim therefore *understates* the arc's north-star progress on the very axis Will cared about most, and its decisive adversary test fails. Per the audit rule ("a claim STANDS only if your refutation FAILS"), this refutation lands.

**Verdict on (b): WEAKENED / does NOT stand as written.** Confidence: high (on the factual finding that 017b executed in-window and is Obs7-shaped) / medium (on disposition — the underlying coarse direction "advancing, not arrived" is still correct, so a *corrected* north-star call would survive: the right statement is "advancing, with TWO down-payments on the phenomenon — route-matters AND a first in-window Obs7 precision-ratio hit (017b Phase B) — while Q5/Q6 and the doubling ladder stay open"). The claim does not stand in its current form because its load-bearing "Obs7 deferred / banked / unattacked / none-in-window" assertion is contradicted by an in-window executed task, and its own falsification trigger (Obs7 precision-scaling execution in window) is satisfied.
